### PR TITLE
More minor issue fixes

### PR DESCRIPTION
**Pull request by lowercasename**

### CODE REVIEW

**Comment by lowercasename** [comment]
My only concern with the link previews, which work super great, is what if we want to change something about their structure later? The icon or whatever (like I just changed the icon)? The way we have it now, link previews are actually locked into the content of the post, and I'm not convinced that's a great idea. Thoughts?

**Comment by toBeOfUse** [comment]
Yeah, you're totally right about that, I mentally went back and forth a couple of times. It makes the displaying code a lot simpler obviously if we just have a bunch of HTML already saved that we can throw on the screen, and it's faster to not generate it over and over again every time posts have to be loaded, and I just personally honestly like the idea that if someone scrolls back far enough into old posts they'll see what stuff used to look like? Like, if we change how the link previews look the old type will still be preserved for future archaeologists? Although the big concern with that is that we'd have to keep the old CSS classes in place... if we do keep putting the HTML for the link previews directly into the database like this we should probably inline that. Or we could switch to using the embedded video handlebars partial in the post rendering process... the thing was, I didn't immediately see how that could be rendered and placed where it belonged within the post. It could be done with a call to hbs.render() within showposts, I guess, and then put the result of that at a position within the post content, that you save in the post document in the database, originating from where the original link was placed. Or I guess you could just place it at the beginning of the post every time... I'm against putting it at the end bc it feels like if you embed a video, it's more often than not the focus of your post, and should feel like it. So yeah, there are options.

**Comment by toBeOfUse** [comment]
Yeah, I was kind of hoping you'd change the video play button icon honestly, thanks for that

**Comment by toBeOfUse** [comment]
Hey, I'm going temporarily insane so I might not be on here for a while, feel free to merge and push whatever, your link preview idea did really improve the embedding situation I had in place and I'll be excited to see whatever you do with the rest of this

**Comment by lowercasename** [comment]
That's absolutely fine, take care! <3

**Comment by lowercasename** [comment]
I've implemented the basic mute user functionality which has been a _long_ time coming. Currently, just that user's OC posts get simply filtered out with a few lines of code, and nothing else - you can still see their icon in member lists, their comments, and posts of theirs which have been boosted by someone else. I think maybe it would be good to hide boosted posts and comments, after all, I just have to run and do work now!

**Comment by lowercasename** [comment]
I've been particularly admiring your video embed code and your tweaks to the comment posting code and the notifer 😍

**Comment by lowercasename** [comment]
I'm happy to roll this out, a lot of good changes in this update

**Comment by lowercasename** [comment]
Okay I think that's enough

**Pull request merged**
