### PR TITLE
Ongoing project to get /app under control

### PR DESCRIPTION
**Pull request by toBeOfUse**
Fixing the post editor formatter is important but I also wanted to get all of this extremely boring stuff down in a to-do list so it doesn't get forgotten about.

Agenda:
~1. Rename /app files: communityRoutes -> communityInteractionLogic, helperFunctions -> textUtilityFunctions (no need to be so vague, we can rename later if we want to broaden it), routes -> two files: viewingSweet and postingToSweet. notifier.js can stay like it is.~
_Done, with modifications (user account actions were the main thing I hadn't accounted for)_
2. Finish adding comments to the function definitions in these files and add a table of contents (in comments) at the top of each file so you can glance through quickly and know what function you need to use ctrl-f to get to to fix whatever specific thing you're working on.
_Might still add TOCs but I did discover I can press ctrl-k-0 in Visual Studio Code to view a collapsed version of the current file, which is basically the same thing but doesn't need to be manually updated_
3. Bring the notifications functionality up to spec. Fix issues #29 and #41.
4. Bring the boosted posts functionality up to spec. Fix issue #18.
5. Add some database indexes to server.js, fixing issue #31. This isn't in the /app directory but whatever.
_According to the comments on #31 @lowercasename did in fact do this but that code does not appear to be in this branch, not sure where it is, also someone should probably add an index on image urls and the relationship "from" field._

I'll be using the ~last page~ _starts on page 6, I'm finished with it now, (everything that I'm not clear on is marked with "ding" and ought to be corrected before the code is written I think, no rush though)_ of [this Google Doc](https://docs.google.com/document/d/1R6jw7jHLAzM-PkLaNzbyalOqKVmUIEzNyhNHpMMlj10/edit?usp=sharing) as the spec for the notifications and boosting posts stuff. The complete intended functionality of both of those isn't actually immediately obvious to me so I invented some logic on my own. I'll probably have to change something in the spec at some point but it does give me somewhere to start. Corrections to it welcome at any point before, during, or after this process.

Non-goals atm: deciding/implementing anything regarding database structure and how the code uniquely identifies users so that usernames can be changed will be on the next to-do list of this type. (At that time we'll also have a better chance of figuring out what indexes to add to the relationships collection, bc then we'll know how we'll be searching for those.) Same for boosting posts into communities if that's something that'll be thinged.

### CODE REVIEW

**Comment by lowercasename** [comment]
This is all great and important! I was wondering about renaming the reordering the files along the lines of: frontendRoutes, userApi, imageApi, communityApi, postingApi, viewingApi (which is the rest of the backend routes, like showposts). Happy to go with your changes though!

I’ll be gone for a few days for a conference and to have a break from the Internet and when I get back I’ll finish up the documentation.

**Comment by toBeOfUse** [comment]
For unclear reasons, I've also added a simple statistics viewer at /admin/sweet-stats.

**Comment by lowercasename** [comment]
I _love_ the stats viewer, it made me cackle.

**Comment by toBeOfUse** [comment]
For even less clear reasons, I've added a posts timeline to /admin/postgraph. Don't ask me how it works, because I don't know. It'll take a little while to load the first time you visit it, and it isn't yet self-updating, and it could perhaps melt something or look a little strange when faced with all the posts on the main server.

**Comment by toBeOfUse** [comment]
If you refresh the page while the graph is loading for the first time i think it will interrupt it and break everything, will fix later

**Comment by toBeOfUse** [comment]
removed the loggedInUserData variable as a going concern per my notes in #49, also threw in a users timeline at /admin/usergraph

**Comment by toBeOfUse** [comment]
I added the npm package connect-mongo so that I wouldn't have to re-log-in every time I changed some code in the routes and restarted the server, so you'll probably have to re-run the npm install command in your root directory before you start the server again

**Comment by toBeOfUse** [comment]
Sessions are also "rolling" now, so the timer for logging out inactive users resets every time they show up. I think they're logged out 12 hours after their most recent visit right now, that should probably be made longer, just need to up the number in the session options. You had the code set up to do it in server.js fine except you were setting cookies._expires instead of cookies.maxAge, cookies._expires is not a thing.

**Comment by toBeOfUse** [comment]
Also I've been marking off the notification rules in the Google Doc as I've tested them and they've been followed, just got the community ones left now

**Comment by lowercasename** [comment]
I'm just... very impressed, this is all a huge amount of work that I haven't really been able to will myself to do myself (because I'm trying to actually write my fucking PhD) and I'm really enjoying watching this codebase grow and become stronger, like a Pokemon <3 Thank you!

**Comment by lowercasename** [comment]
Just added the long-awaited PNG settings (in user settings there are now three options for image quality, including **4K** (just like your TV)). I also added width and height to the database, for which I unfortunately had to install the `image-size` module. I love me a module but even I think this is overkill. Sadly, while we could extract dimensions from sharp as it processes the images, we don't use sharp for GIFs so we'd have to implement a different method for GIFs anyway. Also we'd have to write frontend code for /api/image/upload to save image dimension data into the new post form, and deal with it potentially being deleted?? This seems easier.

**Comment by toBeOfUse** [comment]
Could there perhaps exist an npm package that handles animated gifs as well as jpgs and pngs and could maybe give us the image size that we could replace Sharp with?

**Comment by toBeOfUse** [comment]
https://www.npmjs.com/package/gm looks good, it supports animated gifs, retrieves image sizes, and has jpeg compression and autoOrient (like sharp's rotate with no arguments) methods

**Comment by toBeOfUse** [comment]
It also retrieves image formats, so we can dispense with the extra filetype package

**Comment by toBeOfUse** [comment]
The catch is that [according to the benchmarks sharp posted](http://sharp.dimens.io/en/stable/performance/) sharp is much faster at like everything

**Comment by toBeOfUse** [comment]
Is there a reason that you didn't use [Sharp's image size retrieving capabilities](https://sharp.dimens.io/en/stable/api-input/#metadata)? You'd have to call .rotate() first to get it to take that into account but it overall still looks good to me

**Comment by toBeOfUse** [comment]
I have eliminated the image-size dependency! Sharp seems to work fine for determining the size of animated gifs and of course the other image types.

**Comment by toBeOfUse** [comment]
I deleted some stuff above about replacing sharp, it was somewhat misinformed. Is there a reason we have a separate dependency for determining file types, instead of using sharp? I know we aren't using sharp to process gifs, but it could still just load the file, determine the type, and then do nothing else with it in the case that it is a gif

**Comment by toBeOfUse** [comment]
image

When a function is called and returns something, the function call is effectively transformed into whatever the function returned. So if I have a function
`function returnTwelve(){
return 12;
}`
and I call it like so:
`var num = returnTwelve();`
once the function returns, the function call is transformed, now we effectively have this:
`var num = 12;`
so you see how that works. This is crucial to understanding what happens when we chain sharp function calls:
`sharp(req.files.image.data).resize(...).rotate().jpeg(...).toFile(...)`
The sharp function is called, and returns an object that represents an image, causing the following transformation:
`imageObject.resize(...).rotate().jpeg(...).toFile(...)`
imageObject.resize() returns the same imageObject after the resize has been completed, and so it is transformed:
`imageObject.rotate().jpeg(...).toFile(...)`
.rotate() returns the object again, after it does its work:
`imageObject.jpeg(...).toFile(...)`
.jpeg() does this as well:
`imageObject.toFile(...)`
and so toFile() is called on the final version of the image object. Now that we see how this works, we can break the chain:
`var imageObject = sharp(req.files.image.data).resize(...).rotate();`
because we know the stuff on the right side of the equals sign will be transformed, step by step.
`var imageObject = [image object created by sharp after transformations];`
Once we've broken the chain, we can apply some conditional operations to the imageObject:
```
if(imageFormat == "jpeg" || req.user.settings.imageQuality == "standard"){
    imageObject = imageObject.jpeg(quality: imageQualitySettings.jpegQuality);
}else{
    imageObject = imageObject.png();
}
```
Because, again, .jpeg() and .png() return the new version of the image object. Then we can finally save it with toFile().
This is all instead of having to write
```
if(imageFormat == "jpeg" || req.user.settings.imageQuality == "standard"){
    [the entire chain with .jpeg()].toFile(...);
}else{
    [the entire chain with .png() instead].toFile(...);
}
```

So.

Functions that return promises, like toFile(), are the only ones that work a little differently. toFile() returns a promise right away, before it's finished actually saving the file, and we call .then() on that promise to give it a function to execute once toFile() is done actually doing its job.

**Comment by toBeOfUse** [comment]
I replaced the file-type dependency with just loading the image with sharp and getting the file type from that. We also have a new folder, databasetransforms, which contains addImageSizesToDB.js, which when run (in its own separate node.js program) will retroactively add the width and height fields to all the (actually valid) image documents in the database. ALSO I'm messing around with how boosts are stored in the database, you might be able to see that in there, nothing is finalized yet though.

I'm curious to see what you will accomplish with displaying different with image heights, for starters I can't help but notice that to use the fields you added, the image documents will now have to be retrieved for each post that is rendered in handlebars, which is whatever I guess, but they certainly could be in the post document next to imageDescriptions. Secondly, is this necessary? It almost seems to me that you could just set the max-height for images to be larger, like to 600px, and the problem would just about take care of itself. I think you said you wanted square images to be displayed full-size, which would mean a height of 700px on desktop, but I'm not sure that's feasible, it would look like this:

image

Basically, if you set max-height for every image to 600px or so, wider images will pretty much stay the same (because they are already bumping up against the max-width property and so cannot be enlarged), square images will be displayed at the max size that is feasible:

image

and vertical images, just the same, I don't think you want them much taller than this:

image

On mobile maybe use a max-height of 500px. Wide images will be displayed the same, square ones will be displayed at the maximum possible size given the width of the screen (it doesn't look square but it is, I measured it):

square on mobile

And vertical ones will be pretty tall:

vertical on mobile
 
There is the potential to display them a little bit taller on phones with really big screens, and maybe a little bit shorter on phones with really small screens, but that has nothing to do with the dimensions or aspect ratio of the original images, that just means setting more fine grained @ media properties, like different max-heights for phones with 300px wide, 400px wide, and 500px wide screens. (You could do the same of course for non-mobile devices, like laptops with lower screen resolutions than what my screenshots above were taken at and thus would like lower max-heights, and for people with 4k monitors and stuff that would be able to make use of higher ones.)

Basically, this just means displaying square and vertical images as tall as possible without making them go off the top and bottom of the screen, instead of trying to resize them somehow based on their aspect ratio. This isn't my department though, you figure it out, maybe I'm just completely overlooking what you had in mind.

Sorry to write so much tonight, it just kind of happened, I don't mean to take you away from your PhD thesis which I understand of course is very important to you. I'm doing my best with the code, although I notice upon using the postTimeline.csv that you committed the graph's x-axis labeling is a little iffy with longer timescales, I'll try to fix that, and also I'm not sure I'm creating the best indexes and I probably should go back and add a bunch more projections to the collection.find() calls. I really like the new image upload settings btw, very clean and understandable and useful.

**Comment by toBeOfUse** [comment]
Upon further thought, you probably just meant that you wanted square images to be displayed full-size _on mobile._ Which the thing I showed above kind of does take care of? But you probably want to keep square and wider images around their current height of 400px on desktop, and just give vertical images that extra boost. In that case, I guess I would propose having a boolean variable isVertical for each image, in the post and/or image documents, set to true if the image's aspect ratio is less than or equal to 0.75, and if it's true the image gets the vertical-image class with css that bumps the max-height up to 500-600px so it looks a little like the third image above.

**Comment by toBeOfUse** [comment]
Can I. Can I remove the imageTags field from the post documents. I have absolutely no idea what it does

**Comment by toBeOfUse** [comment]
Introducing the boostsV2 field in the post documents! The idea is just that instead of boosts being separate post documents in the post collection, so that we have to try to hide all the boosts except for the one we want and the information about who boosted a post and when is spread out across them, boost documents should be embedded in the post that they refer to, so that they basically function a lot like comments currently do (like, one document for each post and it's being moved around by the modification of lastUpdated). Also, I've decided that every post is implicitly boosted by its author at time of posting, so the default value for the boostsV2 field is just one entry with the post's normal author and timestamp. This means that all we have to do to find both the posts that a user has created and the ones they've boosted is search the posts.boostsV2.booster field; both authorship and boostership are caught up in that. (It's a little bit weird because boostsV2 is in fact an array but just go with it.) For example, when loading a user's home feed, we do this for everyone that they follow. This is helped along by the index I've put on that field, which seems to be getting hit the appropriate amount.
To populate this new field in your database, run populateBoostsV2.js (it's a separate Node.js thing.) It's pretty well tested and self-validating but you certainly could back up your database before with mongodump (in C:\Program Files\MongoDB\Server\4.0\bin on Windows) so that you then can restore your database from that backup if you want with "mongorestore --drop" on the command line in the same folder (shift-right-click in the blank space in a folder on Windows to get the option to open a command line window starting in there).
Proper boosted post labels, un-boosting, and probably some other stuff is not implemented yet, I'll edit this out when it is.

**Comment by lowercasename** [comment]
Boosts! Glory be! Nice one, I’ll populate that today.

How _dare you_ suggest we remove the tags code, how _could you_, when it is _so important_?? That was some code to query an image recognition API and get AI-generated information on what images that don’t have image descriptions might contain, but I turned it off because I don’t want to share image data like that. So yes, all the vestiges of that code can definitely go.

**Comment by lowercasename** [comment]
Thank you for the functions lesson, that was super interesting and enlightening! I actually get it now which doesn’t usually happen.

Your last comment about the images is 10/10 what I wanted to do using the width and height data, yes. Also more data is always useful!

**Comment by lowercasename** [comment]
I've added a simple link preview code (which, while simple, requires a lot of module: `npm install got metascraper metascraper-url metascraper-image metascraper-title metascraper-description`). The benefit of this particular module as I can make out is the ability to make our own scrapers down the line which would be useful for custom previews of sweet communities and posts. That said, we could probably do that easier without this module, huh. Because... we control the database. Hm. Oh well - see what you think! It also currently just grabs the first URL and there's no way to turn it off. It would make more sense to add the previews as a post is being written, so that they can be deleted or adjusted at will, but that would require us to catch URLs in the frontend, which would potentially be made very tedious by the rich text editor. This might not belong in this branch either - maybe it's a 'for later' thing.

**Comment by toBeOfUse** [comment]
Yeah, to be honest, maybe a for later thing? Much later? I'm not sure I'm unambiguously in favor of the way this _particular_ implementation kind of visually pulls all the links out of posts and dumps them all together at the end, I'd prefer things to kind of be... mixed in, naturally. Like, this kind of sort of removes authorial control of how any given link is... perceived, they can't just be subtly dropped in anymore, like if you just want to add a source for something your saying for completeness' sake without really expecting people to click on it, now the link is sort of uncomfortably advertised. Or if you just don't want the page on the other side of the link to have its impact staggered, preempted by a smaller, squasheder version of itself. Or if you just don't want the SEOed title of the page you're linking to to be brought up to represent it as text in your post. MAYBE I'm wrong and everyone would LOVE it. Or maybe this would KILL ALL POETRY

**Comment by toBeOfUse** [comment]
If you run that boostsV2 populating script as it is, it will remove all the old boost records, so boosts won't be displayed until also the new routes code. I would be curious to know if the script can in fact run on the server without any errors, but if you do run it there just comment line 70 out for now or else boosts will stop showing up until we push the full update. You then can run it again without line 70 commented out later to clean up, you can theoretically run that whole script multiple times without causing issues, it won't re-add anything that already exists.

**Comment by toBeOfUse** [comment]
I guess it might also move some posts around by setting lastUpdated to be the timestamp of the latest boost if there is no more recent comment on the post, although that would not be a huge issue I think, but you can probably block that by commenting out lines 58-63, and then again you'll have to re-run but with those lines intact when the full code is pushed.

**Comment by toBeOfUse** [comment]
Vaguely passive-aggressive reminder to run npm prune in the root directory to get rid of unused packages cause I removed file-type and image-size or whatever it was called. Also did you know that you can just run the command "npm install" to auto-install all the packages listed in package.json, I only ask because you typed a whole command thing above and it took me ages to figure that out when I was first setting up this server

**Comment by toBeOfUse** [comment]
I am ponderin' the idea of sorting posts by their original timestamp on user profile pages, instead of by lastUpdated, I'm feeling like user pages should be more like a straightforward archive view of posts and the dynamical moving around in response to boosts and comments should just be a thing on the home feed...

**Comment by lowercasename** [comment]
I have no idea how to use git! I even read a tutorial and it didn't help. Anyway the link previews code is in its own branch now (should it be there? who knows!). I also did npm prune and it didn't seem to do anything. Oh and yeah of course, package.json will contain what you need, duh.

I realised that running that code on the current server would probably result in errors or worse (I'd have to import in the new post model for starters) so I've left it for now.

And I like that idea with user pages! It makes sense and is logical and good. Good.

**Comment by lowercasename** [comment]
Oh, apparently it didn't remove that commit with the link previews even though I asked it to. Why, git?

**Comment by lowercasename** [comment]
Okay I just commented the stuff I added in out, sorry! I knew the day I messed something up with my git ineptitude would come sooner or later.

**Comment by toBeOfUse** [comment]
Yeah... the safe way to revert a commit is in fact [the revert command](https://gist.github.com/gunjanpatel/18f9e4d1eb609597c50c2118e416e6a6), not force-push. You can also cause the revert command to fire if you right click on a commit and choose "revert" in Github Desktop, if you're using that. I did use force-push somewhere in this repository bc I was looking for a way to revert without leaving a permanent record on the pull request page but I don't think there is one

**Comment by toBeOfUse** [comment]
Like, you just need the command from the first part of the linked page to revert commits, not the second

**Comment by lowercasename** [comment]
I haven’t had a chance to look at the latest style but I was wondering overnight if a pop up Bootstrap modal listing names would be more mobile friendly. Would appreciate your thoughts on that though

**Comment by toBeOfUse** [comment]
I don't know! I guess it would be more obvious to know how to dismiss it if there's like an actual x, instead of the implied click/tap somewhere else thing. I'm still trying to figure out how any of this stuff should look, I'm not sure how to fold in boosters that the current user doesn't follow

**Comment by lowercasename** [comment]
I’m happy to have a look at it soon - I hate to take design cues from Facebook but they’ve funded the research so we don’t have to! Modals are good for mobile for precisely that reason, yeah, and they’re responsive (and apart from the notifications dropdown we don’t really have much else on the site in dropdowns). And we could just do little tags next to the usernames marking the people you follow - then it’s unambiguous and not confusing.


________________________________

**Comment by toBeOfUse** [comment]
I'm thinking that if there are 100 people that boosted your post, and you only follow 10 of them, the people that you follow should either be listed separately or first so you don't have to scroll/look through the rest

**Comment by lowercasename** [comment]
I thought since it would make at least two people happy and it's really easy, I've made a user setting to change the way posts are sorted in three contexts: users, home and tags, and communities. _Simples_. Which is a joke you probably wouldn't get because you're not from the UK. Context: https://www.youtube.com/watch?v=M0mXUC0cUPg

**Comment by lowercasename** [comment]
Currently it appears that all posts posted by a user get 'boosted by @you' attached and so do posts posted by someone else.

**Comment by toBeOfUse** [comment]
> _Simples_. Which is a joke you probably wouldn't get because you're not from the UK. Context: https://www.youtube.com/watch?v=M0mXUC0cUPg

omg

**Comment by toBeOfUse** [comment]
Yeah, that's probably a good setting to have, I guess notifications will indeed keep older threads going for those users fine especially with an always-there "subscribe to notifications" button, like I had suggested in the Google Doc. However, I do think I'm going to have to add something clever to position boosts according to the time that the person you followed boosted them, even in chronological mode, as otherwise boosts of old posts will put the post way down below posts you've already seen in your feed. Also, we need an "un-boost" symbol, distinct from the "delete post" trashcan (so that at the very least people that have boosted one of their own posts will be able to see a visual difference between the two actions.)

**Comment by lowercasename** [comment]
I think we can just layer the slash icon on top of the retweet icon, as explained here: https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by toBeOfUse** [comment]
Is there a reason that context can be "single" in the showposts route but there's also a completely different route function ("/:username/:posturl") for actually retrieving single posts? This question also applies to the existence of separate "posts" and "singlepost" handlebars files, it seems like you could just render "posts" with an array containing just the one.

**Comment by toBeOfUse** [comment]
You'll need to re-run the populateBoostsV2 if you want to properly test out what's currently happening. If you find something I haven't broken let me know, this one was kind of rough

**Comment by lowercasename** [comment]
> Is there a reason that context can be "single" in the showposts route but there's also a completely different route function ("/:username/:posturl") for actually retrieving single posts? This question also applies to the existence of separate "posts" and "singlepost" handlebars files, it seems like you could just render "posts" with an array containing just the one.

Yeah the 'single' in the showposts route is deprecated; the reason I made a special separate route function is so that the single post's metadata would appear in the header of the page - I couldn't think of any way to do it if the post was loaded via API.

**Comment by lowercasename** [comment]
I finished styling the boost list modal!
There are a couple of bugs I've noticed in boosting, I hope my telling you will be helpful! I tested these on a newly made post.

- If I and a person I do not follow boost a third person's post, otherBoosters is empty (but it should contain the person I do not follow).
- If I click the 'boost' button once I've boosted a post, I appear to remove the post permanently from my home feed. It still appears in the post author's feed. I think I'm also able to delete other people's boosts by clicking that button, but I'm not entirely sure what's going on there.
- If I click the boost button on a post someone has written and boosted, I also remove that post from my feed. I think.
- I also managed to hide every post in one user's user feed for myself, but they still come up on the home feed (except the ones I hid by boosting). At this point I decided maybe I should let sleeping dogs lie.

**Comment by toBeOfUse** [comment]
Yeah, we have _several_ problems.
For user pages in fluid mode, whose boosts do we want to take into account for sorting? Everyone's, or just boosts created by the people that the user viewing the page follows? (In chronological mode, it's just the boosts made by the user whose page we are on that should have any effect at all. ) I'm going to make it just the people you follow for now. And the same goes for the home page, just the people you follow's boosts will move a post around, unlike comments, which will still move a post around on your feed no matter who leaves them. I guess. Maybe there should be a setting or something so that a post is only bumped to the top of your feed if specifically someone you follow comments on it, or maybe you can unsubscribe to a post so that it no longer goes to the top of your feed at all if you're tired of seeing it (which would probably be best implemented as just "hide this post on my home feed"), or this or that or the other thing, the more I think about it the more complicated this post sorting gets. This is why you write the spec first. Put that next to the idea of storing the users that one follows and has flagged in one's user document, so that they don't have to be gathered from the Relationships collection at the top of showposts every time one scrolls down to load the next few posts. And whatever other strange things I'm typing into the bottom of that Google Doc these days.

**Comment by toBeOfUse** [comment]
[I added to the doc](https://docs.google.com/document/d/1R6jw7jHLAzM-PkLaNzbyalOqKVmUIEzNyhNHpMMlj10/edit) my fuller outline of what I'm going to try to implement now that I've actually thought about it, the relevant section is somewhere across pages 8-9. I'm unconvinced that this is as simple as your meerkat friend seemed to believe

**Comment by toBeOfUse** [comment]
Or maybe on a user profile page the only boosts should count are the ones made by the user whose profile page we are on, even in fluid mode. I think I'll go with that.

**Comment by toBeOfUse** [comment]
Is there a reason that it's called homeTagTimelineSorting? What is "tag"

**Comment by lowercasename** [comment]
Your spec is good, I can see why it's needed! We're going to run in more problems if we get around to community boosts. Also just as a sidenote, in view of avoiding writing complicated code, I am not much in favour of threaded comments. I guess the code won't be _that_ complicated, but I like non-threaded comments for a lot of reasons, and not writing lots of new code is one of them.

**Comment by toBeOfUse** [comment]
> > Is there a reason that context can be "single" in the showposts route but there's also a completely different route function ("/:username/:posturl") for actually retrieving single posts? This question also applies to the existence of separate "posts" and "singlepost" handlebars files, it seems like you could just render "posts" with an array containing just the one.
> 
> Yeah the 'single' in the showposts route is deprecated; the reason I made a special separate route function is so that the single post's metadata would appear in the header of the page - I couldn't think of any way to do it if the post was loaded via API.

I suspect you could just `res.render('singlepost', {...metadata:metadata...})` at the end of /showposts/... if you were looking at a single post and `res.render('posts', {...})` otherwise

**Comment by toBeOfUse** [comment]
I just did the thing I said above, seems to work out, the tags are intact. /:username/:posturl just redirects to /showposts now but without changing the url the user sees in their browser, which I think is for the best. This saves about 332 lines of code, and different people have very different mentalities to codebases (some people build camps, some people build forts) but I personally like codebases with as little repetition and basically as few lines as possible, as long as it isn't making things weird. Pretty much everything I've contributed for this pull request has been about stuff that marginally affects the actual users if at all, and I am sorry for that, it's kind of just an instinct I have to... make things cleaner and more in line with some ideal of formal logic that doesn't necessarily have immediate practical effect. So there you go. Like I fully understand
image
and don't think that I'm dismissing the fact that you created all this in the first place as I tear through apparently searching for things to pounce on and rip to shreds for no immediately apparent benefit

**Comment by toBeOfUse** [comment]
Some stuff is fixed compared to last time, by the way. It's hard to tell what exactly because my test database posts are a gigantic mess of keysmashes and image spam so it's not immediately obvious what order anything should be in the first place. Need to do more work on the boosts header tomorrow, for user profile pages need to only display "Boosted by [that user]" in the header and have all the rest in the modal I think, bc no other boosts (should) affect the order that posts are displayed in on those pages and I think that should be clear.

**Comment by lowercasename** [comment]
Ah yes, that stage in every site’s design when it implements code specifically designed for my friend Lydia

**Comment by toBeOfUse** [comment]
Yeah, that was just written to run on the test server, should probably be removed from the production version as that version will make it harder to have the problem I was trying to reproduce anyway I guess bc of the rolling logins, idk

**Comment by toBeOfUse** [comment]
Intriguingly, we're now at the point where trying to open a broken user profile image in a new tab will just lead you to a post randomly chosen from the database
image
image

**Comment by toBeOfUse** [comment]
Specifically, the very first post stored in the database, I believe

**Comment by toBeOfUse** [comment]
God computers are smart. I just added 1200 randomly generated posts to my test database and it didn't even make a dent in the average response time of 95 milliseconds for retrieving the home page for a random user, even on my poor old laptop. I was testing to see if my third rewrite of showposts (over on the /profiling branch on my repository) was any faster than this branch's, which it was, by 0.25 milliseconds, which would probably disappear if I rounded more carefully. I'm going to try generating 120,000 posts next, we'll see if a greater difference appears

**Comment by toBeOfUse** [comment]
It keeps getting to about 118000 and then crashing, not sure what the problem is

**Comment by toBeOfUse** [comment]
image
yeah baby

**Comment by toBeOfUse** [comment]
image
fixed it. will run comparative benchmarks in the morning

**Comment by toBeOfUse** [comment]
With 120,000 documents in the database, ApacheBench tells me that the average response time across 50 requests for each of the first 8 pages in the "home" context (so requests to /showposts/home/:id/1, /showposts/home/:id/2, and so on) is 784 ms for this branch in fluid mode and 716 ms in chronological mode. In the /profiling branch's version, the average response time is 122 ms, and when I saw that I didn't bother also testing the fluid mode, I think it'll be about the same. This means 120,000 posts are being sorted through to get the most recent ones from the 4 out of 6 total users that my test user follows in about a tenth of a second, on a Lenovo Thinkpad e560, which is crazy. The fast version does in fact use the -timestamp index to sort posts, which I can be pretty sure of bc I removed that index and re-ran the text and the average response time went from 122 ms to 408 ms.

**Comment by toBeOfUse** [comment]
Remind me to set a slightly narrower scope for the next pull request, this got a little out of hand. Does it work now? Are we done? The boost notifications could probably stand to be re-checked, and all the other ones too I guess why not, wait I should check how the #39 mobile text editor thing looks on my phone maybe we can merge it in here too

**Comment by toBeOfUse** [comment]
Yeah, looks great to me! Links, italics, bold, blockquote, the whole thing. There's still the thing where pasted text somehow gets set to a font size of 1rem, though, which results in it being larger than normal in comments. Need to run down the checklist for notifications another time and poke at boosts and comments and post order a little more to see if they can break and maybe figure out why handlebars keeps saying "each doesn't match if" but the actual pages look fine and then we can \~finally\~ merge + push

**Comment by toBeOfUse** [comment]
you'll have to rerun populateBoostsV2 or whatever i called it uh-gain, if you get a chance let me know if it gives you any errors and stuff, although that might not be directly relevant to how it'll do when run on the server anyway bc that and your database formats have diverged

**Comment by lowercasename** [comment]
👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

_YOU DID IT_.

Those stats are wildly impressive, well done - and thank you for properly testing the code at scale, too! I will give all this a read and do some more testing in the week. For sure smaller projects later but this seems to have been pretty vital.

Yeah, tell me again which of the database transform scripts I have to run on the server before I push this new code to it, and in which order - I haven't run any of them on the production server yet.

**Comment by lowercasename** [comment]
Okay so this appears to be a bug. Steps to reproduce:

- Create a post.
- Click the 'boost' button. The post now comes up as boosted by you (presumably because the timestamp of the boost differs from the timestamp of the post?)
- Click the 'boost' button again. The post disappears because it no longer has anything in the 'boostsV2' field.

Is this to do with some weirdness related to me not running the databasetransforms scripts in the right order on my test server? But I'm doing this with newly made posts.

A similar bug appears to occur when I boost someone else's newly made post, then unboost it - the post for some reason ends up at the very bottom of the feed in both user and home contexts.

Looking at it a little closer, it appears that the boosting timestamp is offset on my laptop forward by an hour from the posting timestamp, because I've clearly got the time incorrectly configured somewhere. Could this be what is responsible?

**Comment by lowercasename** [comment]
I mean clearly my database is fucked because if I set timelines to 'chronological' they only show community posts (???), but I'm slightly concerned this might happen on the production server, and want to be sure of the steps I need to take with databasetransforms to mitigate it

**Comment by toBeOfUse** [comment]
Yeah that is super not happening for me, making, boosting, and unboosting a simple was like the first test I did. It sounds like you're making a post with timestamp and lastUpdated in UTC and then the boost is being recorded in local time???

**Comment by toBeOfUse** [comment]
Wait. Was your commit "would back accidental style commit" (abd040c) supposed to modify 13,000 lines (hover your mouse over the id there to see stats)

**Comment by toBeOfUse** [comment]
Ok it's back to how I remember it, should be slightly more reliable again now

**Comment by toBeOfUse** [comment]
If you don't mind, you could let me know how in the name of God you did that in case I'm ever working on a GitHub repository I want to blatantly sabotage

**Comment by toBeOfUse** [comment]
populateBoostsV2.js should be safe to run on the server right now, if you did so I'd be curious to know what the output is. It will remove boosts if it detects a newer boost of the same post by the same booster, but that's kind of the idea and that's the only destructive change it'll make right now. When we push the actual code to the server, it can be run again with line 122 un-commented out and it'll remove the old "boosts" field from the post documents, although this is not strictly speaking necessary, it's just better for me to not have it cluttering my database when I look at it in Compass.

**Comment by toBeOfUse** [comment]
Although I'm 95% sure that script is safe it wouldn't cost much to run mongodump on the remove server to back up the database as it is before running it

**Comment by lowercasename** [comment]
> If you don't mind, you could let me know how in the name of God you did that in case I'm ever working on a GitHub repository I want to blatantly sabotage

jesus christ how did I do that I'm so sorry

uhm, I use git through Atom's interface and I think I had some unsaved files, and then occasionally it just... when I have unsaved files it just... adds every file that has been modified in the previous pushes to the push window and I'm like, I guess it's a bug I'll just force push them? CLEARLY THAT IS NOT WHAT IT DOES, I will use the command line from now on I'm so sorry

**Comment by toBeOfUse** [comment]
Don't worry, we're good, I'm not actually mad

**Comment by lowercasename** [comment]
I didn't think you actually were, I was just very aghast at myself!

Okay that bug is now gone - clearly it was related to me rolling back literally all your changes. spotted some more in singleposts - really enjoyed reading through the code, as well. don't think I didn't notice your plan to become the largest mollusk there has ever been

**Comment by lowercasename** [comment]
I’m going to set aside an hour today or tomorrow to push this to the server and deal with any database fallout (gonna set up a separate new application in PM2 so I can roll back to the old one quickly), so tell me if you’d like to add any more features before we merge it to master! In fact if you want to merge it to master yourself given that it’s your baby and also I’m scared of these resolve conflicts instructions, please go for it any time!

**Comment by toBeOfUse** [comment]
Yeah, I have no idea how to resolve this conflict. The "conflicting file" it refers to hasn't even existed for like 100 commits. You have a better chance as I think the command line instructions here are just telling me how to merge this branch into my branch, whereas we want to merge it into your branch, which hopefully you will see instructions for

**Comment by lowercasename** [comment]
*breathes out*

**Pull request merged**
