### PR TITLE
Um completely re implement the post editor apparently

### PR DESCRIPTION
**Pull request by toBeOfUse**
No point having Handlebars re-render the HTML for each post and comment's image gallery and embed(s) every time it and they are displayed. Now, the HTML for those things is cached in the database until such time as the imagegallery.handlebars or embed.handlebars files are modified and the post needs to be displayed, at which point the html is re-rendered and re-cached. Also, for an actual visible change, comment embeds are implemented now, and embeds are positioned within a post/comment according to where their urls were originally typed.

### CODE REVIEW

**Comment by lowercasename** [comment]
_this is **so** heckin' cool oh my gosh_

_you can move 'em all over_

**Comment by toBeOfUse** [comment]
the npm package "got", which the metascraper package instructs us to use to fetch the pages that it will search through for metadata, does not appear to support the top level domain [.horse](http://endless.horse/), and i am *heartbroken*

**Comment by toBeOfUse** [comment]
Known front-end issues right now: the image progress bar fader is supposed to cover the image but instead only covers the bottom half and the actual progress bar is below the bottom, copying and pasting the slidey inline elements does weird things and should probably just be disallowed, pasting or dropping images into community creator/editor rules/description fields needs to be specifically prevented. Also, there should just be a different css class for the link preview previews (in the editor), I'm pretty sure the actual in-posts link previews once rendered will be distorted due to changes I've made to get the link preview previews looking right. Also, the slidey inline elements should be made a little shorter on mobile.

**Comment by toBeOfUse** [comment]
Oh, and the limit on link previews per post is in fact 10000 right now iirc

**Comment by lowercasename** [comment]
Yes I was thinking actually there’s just no real need to allow formatting in the community editor fields. Like, remarkable, we can use bold. I think people will be just fine without it, and it will prevent headaches with the editor. What do you think?

**Comment by lowercasename** [comment]
Please call the new class link-preview-preview

And I frankly refuse to publish anything which doesn’t support .horse, one of the most canonically important TLDs, but I suppose we’ll just have to deal with it

**Comment by toBeOfUse** [comment]
we now use the "request" npm package instead of the "got" package to do exactly the same thing except it does appear to support .horse urls (well, and also we have to manually add "http://" to urls that don't have it which hopefully won't have any weird consequences)

**Comment by lowercasename** [comment]
Absolutely fine, once you say the magic phrase ‘which hopefully won’t have any weird consequences’ there actually can’t be any weird consequences, it just removes all bugs


________________________________

**Comment by toBeOfUse** [comment]
There are a few outstanding not super urgent todos, but this seems basically functional and stable at this point

**Comment by lowercasename** [comment]
This is just superb, honestly I love it. If you'd like a very small project, I would love to be able to click my cursor below the last displayed link preview or image preview and for a new paragraph to appear there, so I don't have to type a paragraph above, then drag the preview up if I want to write something below the preview. Is this very difficult to achieve? Probably! In which case don't do it!

**Comment by toBeOfUse** [comment]
That seems sensible, I was debating trying to maintain an empty line at the
end of the editor below the last embed but thought it might look like a
weird gap that people would end up feeling they had to delete every time,
but listening for clicks down there is a good alternate take on that,
should be quite possible.

Question: right now images next to each other are grouped, as you've
probably noticed, but a user can stop that from happening by having empty
lines between their images (which could convievably happen by accident,)
causing multiple full-size single images to show up above and below each
other, should the users have that power. Also, I think empty lines will
never show up in the final post right now as blank spaces because browsers
just don't render empty <p> elements, should those be converted to <br>s?
Probably, now that I think about it, but not at the beginning of the post
or the end

**Comment by toBeOfUse** [comment]
The problem with removing blank lines at all is that the embedded elements are stored with a "position" field that basically says what line they're on, and going through and taking out blank ones throws that way off. I failed to account for this and now everything is going horribly wrong, I notice that the parseText function does remove all blank lines (by removing lines that are only html tags such as <p><br></p>) and did you really want that or did you just want to take the blank lines away from the beginning and the end and maybe collapse any instances of multiple blank lines in the middle into just one? Either way a few modifications will need to be made before this goes live. Also, the line breaks breaking up image groups question again.

**Comment by lowercasename** [comment]
The reason that's in tbe parser is because I thought if someone put a lot of blank lines in a post, they were probably making either a mistake or being tedious. If `<p></p>`s don't show up without anything in them, which I to my embarassment can't remember but which you're probably right about, then we could just keep them in - although does Quill put nbsp;s or a <br> in them or something if they're blank? Generally speaking I would prefer no huge gaps, but if the remote danger of huge gaps can prevent everything falling apart in parsing, then roll the remote danger of huge gaps. I guess collapsing lines together would make sense.

In terms of image groups, maybe we could do some CSS sibling selector trickery to squish together neighbouring image previews? That would clearly denote that they'll be merged into one gallery. If someone wants to merge them, but there's visually space between them, they can fix that with judicious backspace application. I see no issue with someone posting multiple single images in sequence. The only issue is that we might have to transition to a Javascript-based 'Show More' system, based on the height of the content div, not just on wordcount.

**Comment by toBeOfUse** [comment]
I am scared of CSS especially when there are plus signs and colons and so I made ipc-group, ipc-group-top, and ipc-group-bottom css classes and applied them selectively with JavaScript. "ipc" = image preview container

**Comment by toBeOfUse** [comment]
Ok, in theory everything works! I mean, who knows, I have no idea what actual code executes when one makes a post anymore. Feel free to make whatever revisions and then also because at some point I shortened the code for gathering the user lists in /showposts the post visibility rules should be double-checked as a proxy for figuring out if those came through ok. And maybe look at the old posts on your test server and make sure their images and video embeds still look right with the new css + rendering stuff. Unless something really comes up I'm going to leave this here

**Comment by toBeOfUse** [comment]
Oh and also maybe see if comments still work, I haven't checked those in forever. Also I don't think the text editor script handlebars file is embedded in the single post handlebars file atm (needed for commenting there.) Also I had a vague idea of making the post controls stick to the bottom of the screen even when the post that you're writing is extending beneath it but that isn't too important.

**Comment by toBeOfUse** [comment]
Also the post editor text placeholders you added got left behind in one of the other pull requests, you could bring those over. I'm pleased to see endless.horse in the url thing btw

**Comment by toBeOfUse** [comment]
Frig, I don't think my brute force approach to getting tribute working with quill will go if you're trying to @ mention someone while typing within a list (...don't ask.) Also, I'm not currently sure if tribute will pop up while you're typing in an image description box, and I'm also not really sure if it should (might as well?) but I am sure if it does it won't work properly right now. I'll hopefully fix that later and then that'll be it for me.

**Comment by lowercasename** [comment]
Does this help?? https://github.com/afconsult/quill-mention

**Comment by toBeOfUse** [comment]
That should be kept in standby in case there is some dangerous edge case with tribute that I'm failing to account for as I replace a bunch of tribute code that i don't know what it does or why it's even going wrong with calls to the quill api. Because if we do use that native quill one we lose display images and usernames in the suggestion box it looks like. And also, I haven't had a chance to look at it, but it really should actually be working everywhere now that i think about it unless tribute does come up when you type an @ in the image description box which, now that I'm thinking about it, I kind of doubt, so provisionally we're back to only worrying about whatever I wrote in the couple of comments above.

**Comment by toBeOfUse** [comment]
What I'm saying is, I'm ready to be done with this one, you should check the things over just to be safe and revise anything you feel like revising and feel free to merge and push

**Comment by lowercasename** [comment]
I've tried to fix comment abbreviation and I think it works now but I appear to have broken some lightbox creation 🤦‍♂

**Comment by toBeOfUse** [comment]
I think I broke some lightbox creation, actually, the post content html generator isn't giving images their data-group attribute. I'm going to set it to the post or comment's id, like it was, although this does mean you can slideshow your way through all of the images in a post or comment even if they're not grouped (next to each other), it would be pretty easy to change that by giving each image group within a post or comment its own short-id but I don't think that's necessary

**Comment by toBeOfUse** [comment]
Actually, instead of using data-group to find our groups of images, since we're iterating over each post and comment to check if it's too tall already, we can at the same time grab the images in each comment and post and lightbox them as a group right there. And if we only do this after the putting the long posts/comments under a cut, whatever was happening to make the lightbox get un-attached from the images when that happened won't be happening anymore.

**Comment by toBeOfUse** [comment]
See if it works now

**Comment by toBeOfUse** [comment]
An ethical dilemma is that we could be routing all the youtube embeds through youtube-nocookie.com, but it looks like autoplay=1 doesn't work with that so the videos couldn't be made to autoplay as soon as you expand them, and also googling it reveals that youtube-nocookie.com does still set some cookies, which is... typical. My browser shows 13 cookies in use when on youtube-nocookie, although that's vs 25 when looking at the same embedded video through the regular youtube.com domain. I'm not sure if it's worth it?

**Comment by toBeOfUse** [comment]
Would you mind if I made a clean copy of the post creator code and made it a separate repository on my page, probably with a codepen demo (with a dummied-out uploader function) and a few extra things to make it configurable if anyone else wanted to use it? Honestly, if that Quill @ mentions repository you linked to can get 81 people apparently using it someone should be interested in a lightly configurable version of this, and maybe I can get Quill to link to it in their list of good Quill projects thing

**Comment by lowercasename** [comment]
Yeah yeah yeah hell yeah do that! (Also you don’t need to get my permission to do stuff with all the dreamy open source code you wrote!)


________________________________

**Comment by lowercasename** [comment]
> An ethical dilemma is that we could be routing all the youtube embeds through youtube-nocookie.com, but it looks like autoplay=1 doesn't work with that so the videos couldn't be made to autoplay as soon as you expand them, and also googling it reveals that youtube-nocookie.com does still set some cookies, which is... typical. My browser shows 13 cookies in use when on youtube-nocookie, although that's vs 25 when looking at the same embedded video through the regular youtube.com domain. I'm not sure if it's worth it?

I think it isn't worth it. If people want not to get cookies they probably have other creative ways to get around that.

**Comment by lowercasename** [comment]
I think I'm gonna merge this! It looks swell. <3

**Pull request merged**
