### PR TITLE
New lightbox

### PR DESCRIPTION
**Pull request by lowercasename**
A better (and maybe even more lightweight, considering that adding galleries to featherlight required a whole new plugin?) lightbox! I think this is fine to merge!

### CODE REVIEW

**Comment by toBeOfUse** [comment]
This is really cool, I like this better than the old one. And it's better at the scrolling through all of the images thing, and there are touch controls for mobile I think, I can't get it on my actual phone over this wifi, but I did look at it in Google Chrome's mobile Chrome emulation thing. There is small glitch though, occurring occasionally on desktop and mobile, every now and then tapping/clicking on an image just opens that image, like the page ends up on the url of that image? I'm not sure why, but in trying to figure out what plugin you're using by Googling (maybe sources for dependencies and their documentation should be put here or in the spec somewhere? it looks like there are a couple "simple lightboxes") I found that simplelightbox.com actually exhibits exactly the same behavior for me, clicking on the alleged demos on their home page sometimes just navigates my browser to the image I'm clicking on. Which is certainly something. Technically I can't prove that this isn't my wifi failing to deliver some script to me again, but previously I could see that it failed to fetch the thing  by watching the console, and nothing like that is showing up in this case.

**Comment by toBeOfUse** [comment]
I am sorry to put this here with no sane explanation, I tried logging all the mouse events and comparing those preceding a working image click to the ones that cause a glitched image click and they appear identical, I'm not sure what else to do except set a breakpoint and step through all the code that happens after a click, which is not too much fun with minified scripts

**Comment by toBeOfUse** [comment]
If you wanted to try this at some point with and without network throttling set to a speed of 50 kb/s, which is roughly my max today, that could certainly be a thing, in some bizarre bank shot kind of way

**Comment by lowercasename** [comment]
Yeah, that's the right plugin - I can't make that happen for me at all, but I guess we could make all the image links return false to prevent that behaviour? People can right click on them if they want to access them raw anyway.

**Comment by toBeOfUse** [comment]
Ok, no simple-lightbox code is being executed when this glitch happens. Medium editor does something to react to a change in focus, jQuery returns... something, twice:
image
And then the browser navigates to the image.

Sure, how do you do that? Return false? Without like disrupting the event chain? Honestly, there are much much worse failure modes then clicking on image -> your browser navigates you to the image, although it is a little weird when it happens with a comment you just left and you hit back from viewing the image and Chrome doesn't re-fetch the page you're going back to and so the comment you just left, which contained the image you clicked on, isn't even there.

**Comment by toBeOfUse** [comment]
image

**Comment by toBeOfUse** [comment]
Also, when you make a comment with a new single image and it gets dynamically added it gets an extra selector's worth of style information compared to the version that's loaded if you refresh (".post-images.one-image > img") and that makes it not centered somehow?
image

**Comment by toBeOfUse** [comment]
image
Also clicking on it (the not centered one) does nothing it looks like. Also that featherlight thing could probably be removed although I don't think it's hurting anything. Oh the one that's not centered is not in an \<a>

**Comment by toBeOfUse** [comment]
Okay, I think I fixed that, when my laptop is charged again I'll try to get the lightbox to attach to the dynamically added comments' images, I don't think it is at present, or at least it seems to be consistently failing in the manner described above with them

**Comment by toBeOfUse** [comment]
Ok, I think I fixed that problem I was complaining about where clicking on the image just activated the link to it, there was a bug in the tribute attachment code that was crashing javascript when the scripts happened to be loaded in a certain order, and it was stopping the lightbox from being attached to the images, which was a little further down in the same function

**Comment by toBeOfUse** [comment]
This still leaves unanswered the question of why this same thing was happening on the actual simple lightbox website! But forget about that for now I guess

**Comment by toBeOfUse** [comment]
Added server-side check to make sure no-one is sending a request that creates a reply more than 5 comments deep. So, comment depth is now computed server-side, instead of being sent by the client in the createcomment request, because that could be falsified, and a comment's depth is no longer stored in an attribute in the DOM bc that's now unused. I guess this whole thing probably works atm, yeah! It'll be really interesting to see how these changes are adopted by the userbase.

**Comment by toBeOfUse** [comment]
image
Raphael, you know I love you, but I've gotta ask if you have in fact heard of `/* */`

**Comment by toBeOfUse** [comment]
I've added some commits that move us towards the vertical image thing, all new single image posts with an aspect ratio less than 3:4 should get the vertical-image class right next to the one-image class, and all vertical images period should get the vertical-image class next to the post-single-image class in case I think of some way to use that. I think all that's missing is the CSS, which could be added in a separate pull request as you're eager to merge the currently working (?) stuff. (Running /databaseTransforms/addIsVerticalField.js should make this also work for previously uploaded images.)

**Comment by toBeOfUse** [comment]
Couple of small quirks on mobile that an insufferable pedant would perhaps point out:
Screenshot_20190621-005725~01
Screenshot_20190621-005843~01
Screenshot_20190621-005514~01

**Comment by lowercasename** [comment]
> Raphael, you know I love you, but I've gotta ask if you have in fact heard of `/* */`

Look, I select the text, I press the Cmd+/, I don't ask the questions

**Pull request merged**
