### PR TITLE
Linting, documentation, and local-dev improvements

### PR DESCRIPTION
**Pull request by wlonk**
*Please stress-test this by hand in local dev as hard as you can!*

This is a huge PR that _risks_ introducing regressions. I've hand-tested it, but unless and until we get automated testing set up, I cannot be confident that there are no regressions without people who know the codebase better than I do hammering this in every combination they can think of to test for them.

The Readme should include a basic guide for getting set up for local dev from scratch. It's not the most lovely prose, but it'll do. Once you've done that, you _should_ be able to use the site entirely as you would otherwise; this PR is supposed to avoid feature changes except for one, and that is preventing actually sending email in local dev. Any time you'd expect an email, just check the console output.

~This is a work-in-progress. Please don't merge yet! I'd like to do more cleanup and a bunch more work on ensuring that it doesn't introduce regressions.~

Goals of this PR:
 - Enforce consistent code style using [ESLint](https://eslint.org/) and [Standard](https://github.com/standard/standard).
 - Add minimal documentation to help others get a development environment set up.
 - Add console-output email backend to facilitate local development.
 - Move from `npm` to `yarn` (for speed, mostly).

Non-goals:
 - Any changes in behavior.
 - Clean up of code structure and architecture.

I am conscious that this diff is too large to effectively code review; this is part of why I am trying to restrict the goals of the PR, and will write up a review guide when it's ready.

### CODE REVIEW

**Comment by toBeOfUse** [comment]
To be clear, I had to Google to be sure of what the word "regression" means in this context and am generally underprepared for reviewing anything more complex than the median bagel (such as roughly half of all bagels), but I am happy to obtain experience in what the development process and environment are like, supposed to look like, so I will be investigating this shortly

**Comment by wlonk** [comment]
@toBeOfUse cool, thank you! That helps me calibrate my language-use too. I tend to default to a certain way of talking about code on GitHub, but now I know more about where you're at and can try to be in a more teacher-mode!

I'm more than happy to talk through this PR extensively and to talk about goals and means and not operate from a position of presuming that it should be merged. Let me know when and how I can be useful to you.

**Comment by toBeOfUse** [comment]
@wlonk your understanding is highly appreciated. It does seem like this PR is a good step for this codebase to take; I do appreciate the goals of enforcing standards and linting even though I don't have a ton of experience with projects like this that are large and long-term enough for cleanliness to be an ongoing concern. I'll be leaving a few review comments and you could help me by letting me know if I'm giving feedback according to the right principles, give or take

**Comment by toBeOfUse** [comment]
Not sure what the etiquette is as far as me pushing directly to this pull request but there was a small problem where the new version of the handlebars package destroyed the whole functionality of the website (with the breaking change listed [here](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v460---january-8th-2020)) so I just added a resolutions line to tell yarn to use the version before that one. So `yarn install` will need to be run again to apply that

**Comment by toBeOfUse** [comment]
Progress report: `postingToSweet.js` and `utilityFunctionsMostlyText.js` still have >15 issues each according to the linter, so I might try to clean those up a little more later. Then the two main client-side scripts, `/public/js/newPostOrCommentScripts.js` and `/public/js/textEditorScripts.js`, have a hundred something not-automatically-fixable problems each, although many are things like "`$ is not defined`" which is like yeah, the jQuery script defines `$`, so I'm not really sure those scripts are thoroughly lintable. I'm also experiencing apparently random server freezes that last for about 30 seconds each that I'm not sure what to make of; either something's going wrong with my computer (they happen even when just running `node server.js` so there's nothing wrong with the debugging setup) or requests are getting bogged down by something before they're even saved in the logs, which should happen before they reach the main routes code.

**Comment by wlonk** [comment]
No worries about the push to the PR, that's welcome.

We can tell ESLint that `$` is a global symbol, so it'll stop complaining about it. I'll put changes like that in.

"Small" problem that entirely broke everything, that's _fine_. Thanks for the fix; that explains the behavior I'd been seeing initially with everything broken, but I'm not sure why it eventually _stopped_ being broken locally.

**Comment by toBeOfUse** [comment]
The latest version of handlebars is safe to use again thanks to the additional module linked to in #174. @wlonk can you see my in-progress review comments? I've just noticed that they're not visible when I'm logged out of Github.

**Comment by toBeOfUse** [comment]
The biggest problems with this PR for me right now are the multi-second request times as shown below:

image

These don't occur on the site itself obviously or on the PR I was previously working on, #155, so it seems like it's some baffling problem with this PR's dependencies or code. In the latest version of this PR, all requests are logged to the terminal in theory as soon as they're received by the server by the morgan package, but that also isn't happening in the cases shown here until minutes after the browser makes the request, so it's as if the server just wasn't receiving them until minutes after they're sent, which is baffling. I also seem to have introduced a minor regression when it comes to adding nested comments which I'm pretty sure I have fixed on my local dev copy but it's very hard to test when I have to wait 90 seconds for making a comment to go through half the time. I'm curious if this problem can be reproduced by anyone else?

**Comment by wlonk** [comment]
@toBeOfUse I'll try to replicate that and fix it if I can. I've made some changes locally that I hadn't yet pushed, so I'll do some differential-diagnosis-y things between your changes and mine around that replication, too, just to see if that can help narrow down a cause. I'll be able to get to it tomorrow, Tuesday.

**Comment by toBeOfUse** [comment]
@wlonk I'm glad I posted that screenshot to prove that that was actually happening, because I can't seem to replicate that problem myself today? Hopefully my computer isn't just intermittently almost-dying in some bizarre fashion

**Comment by toBeOfUse** [comment]
A close look at that screenshot I posted reveals that most of the time was spent in the "stalled" state, based on the fact that the bars are gray, and the [Chrome documentation](https://developers.google.com/web/tools/chrome-devtools/network/understanding-resource-timing) gives the following information about that:

> [Grey]: Stalled/Blocking
> Time the request spent waiting before it could be sent. It can be waiting for any of the reasons described for Queueing. Additionally, this time is inclusive of any time spent in proxy negotiation.

And the following information about queueing:

> A request being queued indicates that:
> 
> - The request was postponed by the rendering engine because it's considered lower priority than critical resources (such as scripts/styles). This often happens with images.
> - The request was put on hold to wait for an unavailable TCP socket that's about to free up.
> - The request was put on hold because the browser only allows six TCP connections per origin on HTTP 1.
> - Time spent making disk cache entries (typically very quick.)

This seems to indicate that the requests weren't even being actually sent to the server on a normal timeline, so this was most likely some really bizarre network problem on my end. Unless this happens to anyone else or there's advice about TCP sockets that anyone wants to give I guess that figuring this out isn't really a priority

**Comment by lowercasename** [comment]
Y'all are doing great work <3 I'm sorry I'm so unavailable, I now have a full time job coding (lol) which is squeezing on my spare time significantly. Like @toBeOfUse I'm also very much at the novice stage and also had to learn what 'regression' means! Thank you for your gradual education @wlonk.

Could the timing issue have been my server being tiny and terrible and literally running out of sockets? I don't know how the internet works
Raphael Kabo
PhD Student, Birkbeck, University of London
E // raphaelkabo@gmail.com (mailto:raphaelkabo@gmail.com)
W // https://raphaelkabo.com

**Comment by wlonk** [comment]
OK, I think this is working. I've minimized linting errors in `app` without getting into things that risk behavioral changes, so I think when you want, we can merge this and then I can start putting in smaller PRs.

**Comment by toBeOfUse** [comment]
The only two bugs that I've found so far are: searching causes an unhandled promise rejection error when the client attempts to fetch the (empty, in my test cases) second page of the search results, and passing a vote to change the image for a community causes a crash and doesn't work because there's an attempt to save the community's record in the database twice in parallel, which MongoDB dislikes. Not sure if either can be traced back to this PR's changes or not, especially the first, where the client-side code seems to be what's malfunctioning, so I'm not sure whether to fix them here or not; I'll probably get a chance to just patch them both here tomorrow, unless this is merged before then, and then later around the first one in particular there are some structural curiosities in the code that a subsequent cleanup attempt can address.

**Comment by wlonk** [comment]
@toBeOfUse can I ask that you hold off on fixing them and let me try to, so I can learn more about the codebase?

**Comment by toBeOfUse** [comment]
@wlonk sure, if you want to. The hint that I'll give for the search thing is that the client side code for fetching the next page is a) based on sending the timestamp of the oldest currently loaded thing and b) is almost exactly duplicated across the various handlebars templates that, when rendered, load pages of posts, such as the home, community, and user profile templates (that's the architectural curiousity I was referring to.) So, I think you can use those templates as a reference for how loading pages of search results is intended to work.

**Comment by wlonk** [comment]
Copying commit message here for legibility.

> And a bonus third, actually.

>  1. Unhandled promise rejection error when searching, as it doesn't always receive an `.oldesttimestamp` to look for. Fixed this by cathing and logging the error case.
>  2. Failure to save a community when updating the image by vote, as it was experiencing a save-in-parallel error. Fixed this by saving the new image to the community synchronously, facilitating saving the community database entry within the current callback.
>  3. Bonus third: creating a new community with no image errored, as `request.files` was null, so checking for `request.files.imageUpload` caused a crash. Fixed by putting a ward before it just checking that `request.files` is truthy.

**Comment by wlonk** [comment]
(Ooh, and I just figured out how to suppress the `no-cond-assign` linting error.)

**Comment by toBeOfUse** [comment]
@wlonk will the user be able to receive a second page of search results if necessary? If not, that should probably be fixed or become an open issue, even if the error is being caught and logged

**Comment by wlonk** [comment]
@toBeOfUse Let me generate enough test data to confirm that. Will do over lunch.

**Comment by wlonk** [comment]
Turns out there was an outstanding bug related to that, where `oldesttimestamp` was being returned in an ID, not a class, for the search results, but the infinite scroll logic was expecting a class. Fixed.

**Comment by toBeOfUse** [comment]
@wlonk excellent, I was hoping it could be nailed down to a specific source. Is this the kind of thing that you'd write a regression test for? Also, using hidden HTML elements to send the timestamp to the client is a system I came up with sort of on the fly, and I can see now that it would be more smoothly implemented by sending a JSON object to the client. Do you think the search page would be a good initial candidate for being rewritten to retrieve JSON results data from the server and render it client-side? I could use some experience with modern JS frameworks, and the search page is isolated enough from the rest of the site that its main body could be rewritten with eg. Vue without even committing to using that framework everywhere, and simple enough to be rewritten later with something else if convenient, although obviously it would be ideal if we all decided on a unifying framework first (I've recently used and liked React but I don't have enough experience with anything else to have an opinion.)

**Comment by toBeOfUse** [comment]
Also, I think this PR is ready to be merged as well

**Comment by wlonk** [comment]
I wouldn't specifically write a regression test at this point, because we don't even have a test framework set up, so all tests I would start with are still just expanding the coverage from 0% towards 100%. Once we're at 100%, regression tests can be written to cover specific bugs that slipped past the test suite, as we find them.

I would be happy to redo search with Vue; my preference would be for Vue over React as (a) I simply like Vue more, (b) Vue is easier to insert partially; React prefers to be an entire single-page app solution. Vue can easily be isolated components. But I'd prefer to start with just filling in some test suite framework in the next PR, then adding a couple features I want to add w.r.t. keyboard navigability and pull-to-refresh.

**Comment by toBeOfUse** [comment]
@wlonk pull to refresh is an interesting one because I already have it in Chrome for Android; I wasn't aware that other mobile platforms don't have that as a browser feature. And yes, I saw where you said you would do that PR next; I was planning on doing the search page in Vue myself and requesting a code review from you when finished, if you think that it is a good starting place.

**Comment by wlonk** [comment]
Oh, please, yes, do! I will happily review.

**Comment by wlonk** [comment]
Hey, can we get this merged, or closed? What is blocking this from changing state? Thanks!

**Comment by toBeOfUse** [comment]
If @lowercasename is otherwise occupied, I'll probably go ahead and merge this tomorrow myself so that development can continue. This PR represents a lot of work and expertise on @wlonk's part and it wouldn't do to just let it gather dust

**Comment by lowercasename** [comment]
Hi both, I'm very sorry, I've had a string of ill health and haven't got round to this at all!

This is a lot of wonderful work, please do not hesitate to merge it in and I'll push it to the server as soon as I get the chance. (And never hesitate to merge in general!)

Also, yes to Vue - I know very little about it but, while I really like what I've learnt about React, as I think one of you said, it's very hard to keep the data structures out of the way of a React-based app and I like how cleanly and clearly Vue seems to distinguish between data and design.

**Pull request merged**
