### PR TITLE
Delete replies immediately, logged out users commenting doesn't do weird things, added @ handles to reply headings. Edit: emoji picker also

### PR DESCRIPTION
**Pull request by toBeOfUse**
So yeah. Nothing too complicated or weird.

### CODE REVIEW

**Comment by toBeOfUse** [comment]
Also I added a preliminary emoji picker! Tested with the latest versions of Chrome, Firefox, and Edge. Final available emojis subject to review of course.

**Comment by toBeOfUse** [comment]
Let me know if you think the emoji picker should be visible on mobile at all. I'll probably look into integrating it into post replies tomorrow night.

**Comment by lowercasename** [comment]
_Love_ the emoji picker. Simple and clean, but definitely no need for it on phones. The button could be labelled with the FontAwesome smiley icon I think.

The current display name and username setup together in comment headers is going to cause grief on small screens but I can't necessarily see an obvious solution for that yet. I've  removed the 'reply' button; if we want we could attach the same code (which I've left in) to the username itself, and make it clickable. Will be confusable with clicking on usernames in any other context though (takes you to their profile page), so am cautious about that.

An alternative is to return the reply to comment button on mobile only, and hide the username on mobile only?

Will push all the latest changes to the server after you have a chance to look at this.

**Comment by lowercasename** [comment]
The other thing is that adding emoji to the comment field is a great idea but we will also eventually need to add (I think, anyway), images, CWs, and a formatting option, and I'm wondering if it won't be better to start a PR for that separately because everything but emoji will involve route and database changes, and work on that to deploy it all at once.

**Comment by toBeOfUse** [comment]
I think the emoji picker is ready now. I'm going to be honest with you: I'd be much more willing to hide the display name on mobile than the username. The username serves a purpose (@ mentions); like, if it was me, I'd have the username first in bold and then the display name as decorative flair off to the side, not the other way around. (Also, I'm used to Tumblr where we get along without display names (at all) just fine.) (Also, I'm not sure why you removed the reply button on desktop just now? I'd definitely re-add that, even if you display:none it on mobile.)

**Comment by toBeOfUse** [comment]
Also, please either add code to the main repository or the open pull request, instead of going back and forth? Unless you have a good reason that I can't see? Right now I'm still working with the pull request version of the code, bc it hasn't been merged into main yet, so I can't see the changes you recently made to the mobile navbar stuff, which were committed to the actual repository. It would probably make things easier to merge when you do merge the pull request too; right now we have a conflict in routes.js because it's been changed differently in this version of the code (the pull request version) to the master repository you've just been committing to. Bc I can't see your most recent changes, I could easily create a ton of conflicts by accident if we both work on the same file here and on the main version of the repository.

**Comment by lowercasename** [comment]
I'm not sure if the reply button is very useful (see my reasoning here: https://github.com/lowercasename/sweet/issues/4#issuecomment-486176340 - basically it looks just like an icon, and since we have a fully functioning @-key activated dropdown with names, it might just not be very useful at all? I'm happy to return it though if you think it's definitely useful (on both mobile and desktop).

**Comment by lowercasename** [comment]
> Also, please either add code to the main repository or the open pull request, instead of going back and forth? Unless you have a good reason that I can't see? Right now I'm still working with the pull request version of the code, bc it hasn't been merged into main yet, so I can't see the changes you recently made to the mobile navbar stuff, which were committed to the actual repository. It would probably make things easier to merge when you do merge the pull request too; right now we have a conflict in routes.js because it's been changed differently in this version of the code (the pull request version) to the master repository you've just been committing to. Bc I can't see your most recent changes, I could easily create a ton of conflicts by accident if we both work on the same file here and on the main version of the repository.

You're completely right - I'm still getting my head around GitHub and Git. I'll make sure to work in PRs in future!

**Comment by lowercasename** [comment]
I've asked sweet's users if they find the username or the display name a more important part of the site - I'm very happy to rotate them if there's a majority who would prefer it that way. I think of display names as the central part of a user's identity on sweet, with the @-usernames basically acting as a hyperlink or shortcut to the user within the internal framework of the code (such as in replies and URLs), but I can absolutely see the case for making usernames more prominent. This is also one of the design decisions I adopted off Twitter, for better or worse.

**Comment by toBeOfUse** [comment]
K I'm done for a while. After you merge this pull request, I was going to edit routes.js by trying to fix all that stuff with IsLoggedInForPost() and IsLoggedInForGet(), trying to settle on a single unique user identifier to use, and then adding comment documentation for all the functions. I'm used to Javadoc style function documentation, which basically just means listing the input, the effect, and the output of every function in comments right above it. Then, IN THEORY, someone should write unit tests that call each exported function and check to see if they produce the expected results by looking at the database, so that those tests can be run whenever routes.js is modified to see if everything works. But I don't want to start on any of that stuff if you're going to be working on routes.js also, so let me know of your plans. I could also work on dark mode or something? I see that you have the start of a css file for it but I don't think that it's used. Ttyl. PS I do like the reply button, I'm not used to actually typing @ handles, it's not a common thing I think. I think it should have hover text that says "reply" though except maybe that would interfere with screen readers or something? Not sure. PPS identifying everyone by handles just makes everything feel more cyberpunk.

**Comment by lowercasename** [comment]
Thank you so much for all these, that's a lot of coding. I think your idea to standardise IsLoggedInForPost() and IsLoggedInForGet() is a good one, as is overhauling the user identifiers. I won't be able to look at this properly for about a week, so the floor is yours. I'm eternally sorry about the quality and unparsability of my code and I think you're doing great in difficult circumstances - if you want to start writing tests (something I've only ever read about), I'd be very grateful (and impressed).

I might have a chance to look at dark mode soon but please feel welcome to start a PR, I think I've currently just got a commented out tag in the site header for that file that I was testing with. A logical place for a dark mode switch would be in user settings.

Vanilla tooltips in Bootstrap come up when you tap on them on mobile browsers, as a workaround for the lack of hovering - it's tedious in this case. I've just made the buttons change color on hover which will help anyway. 

Cyberpunk stylings greatly appreciated and noted - you're swaying me.

Thanks again x

**Pull request merged**
