### PR TITLE
Very small threaded comments update

### PR DESCRIPTION
**Pull request by toBeOfUse**
A specific message for if someone deletes a comment by the time you hit "reply" on your reply to it (inspired by true events), re-adding the depth check for including the reply button when dynamically adding a comment, and slightly more robust client-side javascript error reporting bc what's made it to the production server so far is kind of baffling.

### CODE REVIEW

**Comment by lowercasename** [comment]
> error reporting bc what's made it to the production server so far is kind of baffling.

how _dare you_ call me out in this absolutely factual manner

**Comment by toBeOfUse** [comment]
am i? i was referring to the contents of clientsideerrors.txt on the server, not to anything you had done

**Comment by lowercasename** [comment]
> am i? i was referring to the contents of clientsideerrors.txt on the server, not to anything you had done

oh i see, I was just pointing out that some of my code is _terrible_. I actually can't bring myself to fix the image CSS right now but I will, gonna push one more little fix and merge this

**Comment by lowercasename** [comment]
Oh wait you wanted to fix the orange, the floor is yours, I will also not mind if you make it any other color, or grey

**Comment by lowercasename** [comment]
New favicon! Bee! Beevicon!

**Pull request merged**
