### PR TITLE
Comment images

### PR DESCRIPTION
**Pull request by lowercasename**
Looking at the DB structure I thought there's no reason not to transition to using the 'Image' document to attach image data to posts. This will make it easier to have multi-image posts if we decide to pursue that. I think sadly it's incompatible with the current image API so I've named it `image_v3` - is this the best way forward?

### CODE REVIEW

**Comment by toBeOfUse** [comment]
Can you clarify your thinking on that a little bit? I don't see anything obviously wrong with switching to referencing image documents in the post documents instead of just storing image filenames in the post documents, but I'm missing what problem you're trying to solve with this. Could we not reference multiple images in a post document just by storing multiple filenames in the images field that we have? Also, I am a little worried that this will slow down the retrieval of the image filenames that do need to be pulled up when the post is being loaded, as the database software has to find the relevant image document to deliver them.

**Comment by lowercasename** [comment]
I'm absolutely happy to be overruled, but my thinking is, in relation to multiple images for a post:

images: ['filename', 'filename', 'filename']
imageDescriptions: ['String', 'String']

If the user decides not to input a description for image #2, for instance, with the current display API the description for image #3 will be shown for it.

I guess this could be mitigated with much smaller overhead and no extra DB calls by just putting in a blank string for a description but how reliable is that in Javascript?

**Comment by toBeOfUse** [comment]
Ok, I see now your reasoning. Blank strings are good and fun though imo

**Comment by lowercasename** [comment]
Let's just roll with that, then.

I was also thinking - I'm pretty sure the code we're using for image upload previews can be made multi-file by simple making the `<input>` `multiple`, so perhaps we can do that when we're ready and reduce the size of the image preview window, since it serves no real purpose and will serve less with multi-image uploads enabled

**Comment by lowercasename** [comment]
Oh I see, you quite sensibly removed that script and left only the useful parts of it. That script did have an inbuilt way to handle multiple uploads, mind you, so we'll have to write that ourselves.

**Comment by toBeOfUse** [comment]
Do I have permission to push changes to this pull request? Github Desktop doesn't seem to want to let me

**Comment by toBeOfUse** [comment]
Ok I made a few... interesting changes to image uploading on my branch (so I guess they also automatically went to the other pull request?) that you should probably look at before you write any extra code yourself regarding what we were just talking about. Still needs a bit of work and a lot of cleanup. Feel free to merge them into this branch, I'm still not sure if it's my mistake that I can't add them here myself

**Comment by toBeOfUse** [comment]
Thanks for the permission thing, I won't push anything to the main branch of this repository unless you specifically tell me to. I made some commits to modify the image uploader and to unify the community and regular createpost methods. If you have any feedback I might as well hear it before I act on my plans to adapt the new image uploady thing to work with the comments as well (I assume that's what you were hinting at when you gave this pull request this name.) Or if not, whatever, I'll get around to it anyway. I don't have any Apple stuff and thus am unable to test anything in Safari btw? Best, Mitch

**Comment by toBeOfUse** [comment]
Somewhat pleased with how the comment images (and regular images) functionality is looking right now. Will do some styling changes and \~code cleanup\~ (I remember there's some to be done but I've totally forgotten what) tomorrow-ish. Btw, how many images do you think a post or a comment should be able to have?

**Comment by toBeOfUse** [comment]
Only big outstanding feature is the ability to re-order uploaded images. I think the only way to guarantee that they'll initially show up in the users' preferred orders would be to make them select their images one-by-one, since at least on Windows the multiple file select dialog works vis-a-vis that in mysterious ways. Absent that, I guess we should have some kind of image reordering guy, probably ending up as a vertical-axis-repositional drag-and-drop-type strange and vaguely out-of-place seeming apparatus.

**Comment by lowercasename** [comment]
I have to run but I've done some styling improvements to image display - as a result of which I think we should cap the maximum images per post at 4.

Your work is phenomenal, it looks really great and works so smoothly.

**Comment by toBeOfUse** [comment]
Gotcha. I like the gallery/grid type layout you added, although I do wonder if it's the right choice for EVERY type of image post - I know a huge point of friction for artists that have been moving from Tumblr to Twitter recently has been how Twitter crops their work before displaying it (although the cropping here is at least a little more sane than Twitter's, which uses some kind of ridiculous algorithm to pick out the image's area of greatest contrast... ish.) But I guess THOSE kinds of people can avoid the gallery format cropping by posting images one-at-the-time. Maybe like putting one in the main body of the post and then saying "view the rest by looking at the comments."

**Comment by toBeOfUse** [comment]
Also not a gigantic fan of how featherlight eats the entire scroll bar when the image displaying box shows up, causing all the content on the page in the background to judder back and forth, but it looks like that's pretty solidly cooked into the featherlight base code, huh.
Also I just checked Twitter and Tumblr and their enlarged image viewers do exactly the same thing.

**Comment by lowercasename** [comment]
I think the jitter thing might be a bug on your end because I don't get it??

Yeah unfortunately while I hate to admit Twitter is right it's a toss-up between neat posts and ratio fidelity. I recall Tumblr's got a very advanced choose-your-own layout system which is lovely but definitely overkill for us I think. I also think the pink stripes are cute and hopefully others will think so too and upload single images!

I've decreased the size of the image box in comments which I think looks much better and less intensely crowded, but see what you think.

**Comment by lowercasename** [comment]
I've added in a wee sortable javascript plugin which seems to work just great - the images are even sent to the server in the right order, which is a blessing! The only thing is that it needs to be called after images are added to the container element, which I've had to leave to you because I'm out of time today. It's on line 131 in the uploadscripts file.

I've also changed some of the CSS around the image upload previews for the layout to be a bit tighter, to make dragging and dropping divs less of a pain than it already is, and to integrate the move control. See what you think.

**Comment by toBeOfUse** [comment]
The background page content juddering back and forth thing:
featherlight shenanigans

**Comment by toBeOfUse** [comment]
Yeah, the image uploading code was written with something very similar to this in mind. I like how the plugin you added functions but I can't help but notice that it doesn't do much on mobile.  (Unless, presumably, you have a mouse connected to your phone/tablet via Bluetooth or OTG and therefore can trigger mousedown and mouseup events.) Might have to change it out for something that does, will investigate.

**Comment by lowercasename** [comment]
Ah that’s such a shame, I didn’t test it on mobile. More fool me. Any way to replicate mouseup and mousedown events from mobile? Alternatively that code is v smol, maybe we can add the functionality in?

Last time I checked everything was working fine on Safari by the way!

**Comment by lowercasename** [comment]
https://github.com/timruffles/mobile-drag-drop/

Relevant to our hobbies and interests

**Comment by toBeOfUse** [comment]
Ok this took Way Too Long as I have no idea what I'm doing but we're probably more or less alright for image re-ordering on desktop and mobile now. Let me know if you think the user should have to press and hold for a second to start re-ordering images on mobile, as I'd hate for people to accidentally re-order their images while just trying to scroll up or down. Maybe the 4 arrow thing should be like bright blue and shimmering so they don't touch it on accident like that? Also, things could probably slide around a little more smoothly with like CSS transitions or something? Not sure if those fire upon DOM reordering like what this does or not. Anyway! I'm pretty happy to have pulled this off, I know it's inefficient but I genuinely enjoy reinventing wheels like this sometimes. Hope this works on iOS

**Comment by lowercasename** [comment]
This is kinda legendary, I can't believe you wrote the whole thing from scratch

**Comment by lowercasename** [comment]
Are we... done? Can this be pushed to the server?

**Comment by lowercasename** [comment]
uh, um

uh

Screenshot 2019-05-17 at 10 58 41

**Comment by toBeOfUse** [comment]
Well, I've seem far worse on Tumblr

**Comment by toBeOfUse** [comment]
tumblr_nj09n7qbub1qz8q0ho9_r1_500
tumblr_nj09n7qbub1qz8q0ho5_500

**Comment by lowercasename** [comment]
Frankly in that case I vote we leave it. Replace every font with Zalgo Text and call it a day.

(For me that only happens on desktop - looks like it doesn't register dragend?)

**Comment by toBeOfUse** [comment]
Yeah it's clearly not registering a mouseup to go with the mousedown or those spacers would have been deleted, at the very least.

**Comment by toBeOfUse** [comment]
Sorry, stupid mistake. I refactored like everything when I was generalizing to the touch events and forgot a function call that the desktop version needed and didn't go back and test it.

**Comment by toBeOfUse** [comment]
You can probably still trigger that behavior if you like. Minimize the window or unplug your mouse halfway through dragging an image but at that point I kind of think it's just the user's fault

**Comment by toBeOfUse** [comment]
Feel free to test this for a while longer if you would like, as you're the one that will have to push the emergency fix if something goes terribly wrong

**Comment by lowercasename** [comment]
That's fantastic, thank you - and do not worry at all, you wrote a whole code from scratch and _one thing_ went wrong

image

**Pull request merged**
