### PR TITLE
Fix comment image previews

### PR DESCRIPTION
**Pull request by toBeOfUse**

### CODE REVIEW

**Comment by toBeOfUse** [comment]
Not that this is *particularly* well tested either.

**Comment by lowercasename** [comment]
eh fuck it. Code fast merge young.

**Comment by lowercasename** [comment]
I did the intelligent thing and actually loaded the local version of sweet on my iPhone, which I should have been doing maybe weeks ago?

Still does the scrolling thing I'm afraid.

**Comment by toBeOfUse** [comment]
Again

**Comment by toBeOfUse** [comment]
There went the jQuery, we're in bare metal territory now

**Comment by lowercasename** [comment]
Right, the first one didn't work, the second one lets me scroll _but not_ drag and drop. I've also tried adding `touch-action: none` to everything I could think of, to no avail. So far what did work was this answer: https://stackoverflow.com/questions/9251590/prevent-page-scroll-on-drag-in-ios-and-android but I couldn't work out a way to get scrolling back once the drag event has concluded...

**Comment by lowercasename** [comment]
jQuery is very much the thin, fragile veneer of civillisation which keeps us from becoming the frothing savage beasts we are in our hearts

**Comment by lowercasename** [comment]
Getting there! It works without scrolling and drags great, but only once per item. So after the item is moved, it can't be moved again - and same for each of the other items.

**Comment by toBeOfUse** [comment]
All the code in the StackOverflow answer that you linked to is being executed, except listening to events from the .image-move object instead of the whole document. The event listener is being added with {passive: false} [here ](https://github.com/lowercasename/sweet/pull/34/commits/177592eb780ce68f342d18586d6c278857405302#diff-afd9d57230b29428832cf662d83db6a3R59)and preventDefault() is being called on the resulting event [here](https://github.com/lowercasename/sweet/pull/34/commits/177592eb780ce68f342d18586d6c278857405302#diff-afd9d57230b29428832cf662d83db6a3R59). Also, I just fixed a really obvious error, again please? Is this what they call a "development pipeline"

**Comment by lowercasename** [comment]
This is what they call "development heck", friend

**Comment by toBeOfUse** [comment]
Again

**Comment by lowercasename** [comment]
Same problem - images get one drag each.

I'm trying to keep up to help out but this code is so mystical and arcane it's almost beyond me. 'deltaY' feels like something that should only exist in a Raspberry Pi GPIO-hacking context

**Comment by toBeOfUse** [comment]
Oh, come on. I can understand not knowing some ridiculous programming abstraction term but I at least expected you, as a man of letters, to be up to speed with your Greek.

**Comment by lowercasename** [comment]
_But it just means D-Y_

DEE WHY

**Comment by lowercasename** [comment]
Maybe we should just use GitHub as our social media platform instead of dealing with all this

**Comment by toBeOfUse** [comment]
https://en.wiktionary.org/wiki/%CE%94#Translingual

**Comment by lowercasename** [comment]
Oh, _neat_.

**Comment by toBeOfUse** [comment]
I guess the meaning I'm used to isn't from the original Greek after all. Hm

**Comment by toBeOfUse** [comment]
πάλι

**Comment by lowercasename** [comment]
**επιτυχία**

**Pull request merged**
