### PR TITLE
Threaded comments

### PR DESCRIPTION
**Pull request by lowercasename**

### CODE REVIEW

**Comment by lowercasename** [comment]
Phewf! Okay, I've done most of what I think is necessary for the threaded comments to function.

Deleting comments now no longer deletes the object, but wipes the object's content in the database and leaves a trace which reads 'Comment deleted', because the alternative is working out what happens to that comment's children, and... no.

I've also fully restyled the post and comment CSS, and done some nice things like moved the code which shows a new comment when it's been commented on entirely into the backend, so it's generated there via Handlebars (Handlebars is magical). I also generate new comment forms on the front end dynamically via frontend Handlebars, which is overkill but useful so that medium-editor doesn't freak out. Love me my new definition of 'wheel'.

Also singleposts now uses the same posts_v2 handlebars template as everything else, so that's much easier to be going on with.

I have _not_ yet fixed the logic I took out of the posts_v2 handlebars with showing or not showing certain things in communities. In fact I think currently showing community and tag posts is entirely broken?

We should merge the tag post display functionality into the monstrous showposts function, that might be nice.

Still, **progress!**

**Comment by lowercasename** [comment]
I think it's basically done?

**Comment by lowercasename** [comment]
I fixed some bugs that spat out completely made up numbers of comments per post, so that's good. I've also set up checks per your suggestion @toBeOfUse so if the comment to be deleted has no children, it is deleted completely, and if it has no siblings and its parent has also been marked as deleted, the parent is also completely deleted. That only goes one level though so currently if a marked-as-deleted parent has a marked-as-deleted grandparent and the child gets deleted, only the child and the parent get completely removed.

image

**Comment by lowercasename** [comment]
This is a reminder for me or whoever but once you have a child comment of a comment, and then you click 'reply' on the child comment, the reply button on its parent _also_ doesn't work. Sure it's a simple JS fix in scripts.handlebars, I can't work on this for a week or so

**Comment by lowercasename** [comment]
Turned out to be extremely simple!

I think I'm gonna merge this and push to the prod server if you have no objections, because it's holding back the email update as well and I think it's _relatively_ bug-free

**Comment by toBeOfUse** [comment]
K, I think I've got the lightbox thing also to the realm of the relatively bug-free, if you're going to push might as well push that branch

**Comment by toBeOfUse** [comment]
Merged into #76

**Pull request closed without merging**
