### PR TITLE
S3 images

### PR DESCRIPTION
**Pull request by lowercasename**
I've started moving all the image upload, modification, and display functionality over to S3! It's going pretty well so far.

A question related to this PR: how do I minify JS? Is there some way to do it within the dev setup? I came across a bug where editing a post would fail because tribute hadn't loaded, so I've temporarily commented out tribute but had to switch to the non-minified JS because I don't know how to minify! This is also a reminder to myself to fix this before merging. :P

### CODE REVIEW

**Comment by lowercasename** [comment]
@wlonk, if you've got a moment, could you let me how we minify JS?

**Comment by lowercasename** [comment]
Oh I see, the minifying was done in Ages Past by @toBeOfUse, so I am just gonna cheat and do it online until someone tells me not to

**Comment by lowercasename** [comment]
Well here we go let's see how much I break

**Comment by wlonk** [comment]
Hi I was late to this, but sounds like you got it.

**Pull request merged**
