### PR TITLE
Emoji adder formatting, emojis added to replies, image uploader formatting, code commenting

### PR DESCRIPTION
**Pull request by toBeOfUse**
I thought I might as well open this now. Mainly I'm disappointed in myself that I let the previous version of the emoji picker go live; in this version the cursor doesn't disappear when you use it, which I think makes it much more intuitive to use, it now works more like just pressing keys on an actual keyboard. It also works with replies now, which I think is how most people will use it anyway, if the "replying with candy emoji"continues to be a thing. Keep in mind this means the emoji list will have to be updated in two places to change the available emojis. I reformatted the image uploader so that the preview window no longer has unused scrollbars and crops your image and you can change your mind about what to upload more than once. Also, fixed pre-verification logins from signup page; also, added some comments to routes.js, probably mostly just to make myself feel better? Next I'll try to make the (x) on the image uploader actually cancel the upload if it happens to still be in progress.

### CODE REVIEW

**Comment by lowercasename** [comment]
This is all great, thanks a lot! I've done some tweaks, including fixing the background and margins of the image upload preview, put the emoji into a bordered box and given them a hover effect, which I think does away with the necessity for the 'click to select' help text (let me know if you think it's worth keeping), and made Handlebars partials for the emoji list and the new reply form, which allows us to make simpler changes in multiple places. I've also disassmebled the appended reply textarea business because at some point we had to do it to add tools like emojis and formatting, and this way it mirrors the main reply form more.

**Comment by lowercasename** [comment]
If you want to do something really great, you could try and make clicking the X automatically delete the uploaded image from the filesystem if it's already gone through - that's been playing on my mind.

**Comment by toBeOfUse** [comment]
Uploaded images now go into a temp folder until the post is actually finalized, and the browser sends a request to automatically delete the temp image created when the x is clicked or the browser window is closed without the post being made. This will still leave images stranded in the temp folder if the user's computer crashes or loses power in such away so that the "delete temp images" request is never sent, so I added a timer function that checks every hour to automatically clear the temp folder of images more than an hour old. (We need the temp folder so that we don't have a public API method that just deletes arbitrary images.)

**Comment by toBeOfUse** [comment]
Actually I probably need to sanitize the input to /cleartempimages so that you can't have dot slashes in it huh

**Comment by toBeOfUse** [comment]
I will miss "click here to add" on the emoji adder but I have no data to back up my vague idea that it would work clarifyingly/encouragingly. I do wonder if there's anything that can be done to make the new header look less like a mobile vertical screen header that's been stretched horizontally too far by accident? I can't justify it, but my eye does like icons put in little groups. It's like no one has a desktop with the icons spread evenly out across the background - they're always lined up against one of the sides. Maybe it's just my resolution that's spreading the icons further apart than they were designed to go? My immediate impression is just that there's a lot of empty space. But, I do have a preference for clutter. The meaning of the communities icon is also... not immediately obvious in my eyes, without the name next to it.

**Comment by toBeOfUse** [comment]
I dumped a bunch of random colors into the darkmode stylesheet to test it out, but I'm having trouble overriding the Bootstrap CSS colors for the muted-text and the buttons with animated color transitions after hover mode. If it was my project I would be very tempted to start removing the Bootstrap CSS entirely and replacing it with my own, but maybe you want to look at it first. You can view the effects of the darkmode stylesheet at any time by putting $('head').append('<link rel="stylesheet" href="/css/darkmode.css">'); into the Chrome/Firefox console.

**Comment by toBeOfUse** [comment]
Not that there's any real hurry

**Comment by lowercasename** [comment]
Yes, you're right, I'll do some more work on the desktop navbar - it seems to be a bit empty and spread out, just as you say. Not sure about the communities icon since the logical alternative is 'a group of users', which is so dull I can't abide it. One option is accordioning out the name of the icon on mouseover in desktop mode, but I think that would get annoying.

**Comment by lowercasename** [comment]
I did already put some colors in the dark mode stylesheet (just in the same places they were in the original stylesheet - your way with the colors in a logical place all together is _much_ better), if you want to save yourself the job of picking colors. I hadn't done all of them but I did most of the main ones. Am happy for tweaks to those, too (I want to make it really quite dark, not like the shitty fake Twitter dark, for added cyberpunk reasons).

**Comment by lowercasename** [comment]
And I'm totally for stripping away Bootstrap, it's a completely unnecessary overhead. Useful for quick deployment, but we're pretty far away from it now. That's a pretty big job though. Some of its inbuilt features like the tabbed interface are quite good, so those could be ported I guess.

**Comment by lowercasename** [comment]
Let me know what you think of this navbar design!

**Comment by lowercasename** [comment]
I've been admiring your documentation and the much improved image upload code, thank you! Am highly amused by your confusion with some of the extremely suspect coding decisons I've made during the course of this madness - it's a good way to show me what needs fixing and/or being set fire to.

**Comment by toBeOfUse** [comment]
Points of order:
1. I do like the new design a lot better, I think we're approaching the ideal of like simple, consistent, functional, etc, and not afraid of text.
2. What would you think of replacing the word "home" on the navbar with the sweet wordmark? I think it prob. ought to be in there somewhere and that seems like a logical place, I think it would make decent visual sense even if you keep the little house icon
3. I do notice that when you have a notification, it shifts the stuff to the right of it over, which decenters the profile pic on mobile.
4. The one thing that still looks up in the air to me is the user @ handle element. It does make sense to separate it from the other stuff as the profile picture doesn't match the lineart icons for the other links, but on desktop it's positioned floatily enough that it looks kind of like it's trying to be centered and missing? I wonder if it could be integrated with the others by desaturating the user icon until mouseover, or putting it smaller and/or in a border. Or maybe putting the whole @ handle thing on the right with the search box? Or making room to properly center it by moving "communities" over to the right by search. (They're both kind of portals to Sweet's outside world?) So yeah. I feel like we could A/B a few of those with the current version

**Comment by toBeOfUse** [comment]
But, great look in general, I def. think it's an improvement over what we have. Mascot: hummingbird? 'Cause sugar?

**Comment by lowercasename** [comment]
Or a bee? Hummingbird, while a lovely idea, feels a little on the nose/not distinct enough from Twitter’s logo. Bees are communal and also great.

Will play more with the design soon, good ideas all.

**Comment by lowercasename** [comment]
Incorporated most of your suggestions - I've decided to keep Home as Home because 'Sweet' doesn't seem to make much sense in this context (the /home route isn't really the 'sweet website' in a meaningful way and 'Feed' or 'Timeline' just look confusing - I think 'Home' is one of those traditional abstractions we now have to keep using). Sweet now has a cute bee logo - I might ask a designer friend of mine to create a custom one at a later stage - and it should stay centred pretty much all the time. The username link looks good next to the search box, I think.

**Comment by toBeOfUse** [comment]
Ok, great. I think this version is better. My instincts are still telling me to get the Sweet name/logo on the page somewhere for branding purposes but it's not exactly make or break. Sorry for disappearing briefly - my existence has become relatively complicated for the last while and next week I have a bunch of end of semester final tests to take and a bunch more end of semester regrets to process, so I probably won't end up making serious contributions to the codebase again for a little while longer.

**Pull request merged**
