### PR TITLE
No idea how either of these things broke

### PR DESCRIPTION
**Pull request by toBeOfUse**

### CODE REVIEW

**Comment by toBeOfUse** [comment]
My guess at the flowers instead of spiders thing is that displayedPosts in the showposts function is created as a global variable (it's declared without var) which means that if two requests are being made at roughly the same time, the value of displayedPosts can change in the function call for the one request if code from the other is executed (while the first function call is waiting for an awaited function to complete or for a .then function to be called.) I went to the flower post to see how it would open it in the editor at roughly the same time that you must have been trying out the editor on the flower post, so my request must have changed the value of displayedPosts for yours. I know this view comes from an older programming paradigm that you kids with your Javascript aren't bound to follow along with, but Global Variables are Bad Almost Always

**Comment by toBeOfUse** [comment]
I had a similar thing once where I made a comment (a picture of Bill Callahan as I recall) but when the comment showed up right after posting it, it had someone else's user pic and username attached (it wasn't saved in the database that way, it was fine after I refreshed.) I'm pretty sure that was because of a global variable called loggedInUserData floating around at the time and got changed by code corresponding to a request made by this other person halfway through the code for my request executing. I wrote more explanation about that variable here: #49 but the moral is declare variables with var or const or let or else, at least in node, where things are being awaited and .thened all over the place and node is pinging back and forth between different sections of the code to execute whatever it can while waiting for those things. (Excepted from this are the variables whose values don't actually change, like the ones created from require() that just generally provide functions that should be globally available throughout the code.)

**Comment by toBeOfUse** [comment]
i can't delete that "quick test" comment until this is pushed btw. completely forget what i was testing.

**Comment by lowercasename** [comment]
Thank you for this! Damn that JavaScript and its Loops

*brother may I have some loops image*

**Comment by toBeOfUse** [comment]
Yeah, in any other language you would have to explicitly declare the
variables outside of a function for them to be global and modifiable by any
code at any time like that

**Pull request merged**
