### PR TITLE
Sanitize incoming post and comment content, vague graph stuff

### PR DESCRIPTION
**Pull request by toBeOfUse**
Another pull request! I didn't merge in any stuff from the other ones, this is just coming from the current main branch for now. It sanitizes incoming post and comment html, tracks @ very just 'cause at this point, and does a bunch of weird things to the graphs that I have no idea if they work or not. There was definitely something else quick and easy that I wanted to throw in here but I've forgotten what it is. This should probably be merged and pushed sooner rather than later assuming it works and stuff in case other people start trying weirder things than I did with the thing that I did with the fish. Wait, frig, I think I broke something bc the text of posts isn't going in the \<p> tags anymore

### CODE REVIEW

**Comment by toBeOfUse** [comment]
Ok, that's fixed, we might be ok now

**Comment by lowercasename** [comment]
Yeah this seems great! Nice one.

**Comment by lowercasename** [comment]
Wait no I think all the stats are broken now

**Comment by lowercasename** [comment]
```
4|sweet    | TypeError: Cannot read property 'user' of undefined
4|sweet    |     at /home/raphael/sweet/app/statisticsTracker.js:19:79
4|sweet    |     at result (/home/raphael/sweet/node_modules/mongodb/lib/utils.js:414:17)
4|sweet    |     at executeCallback (/home/raphael/sweet/node_modules/mongodb/lib/utils.js:406:9)
4|sweet    |     at handleCallback (/home/raphael/sweet/node_modules/mongodb/lib/utils.js:128:55)
4|sweet    |     at cursor.close (/home/raphael/sweet/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
4|sweet    |     at handleCallback (/home/raphael/sweet/node_modules/mongodb/lib/utils.js:128:55)
4|sweet    |     at completeClose (/home/raphael/sweet/node_modules/mongodb/lib/cursor.js:893:14)
4|sweet    |     at _endSession (/home/raphael/sweet/node_modules/mongodb/lib/cursor.js:904:37)
4|sweet    |     at Cursor._endSession (/home/raphael/sweet/node_modules/mongodb-core/lib/cursor.js:195:5)
4|sweet    |     at Cursor._endSession (/home/raphael/sweet/node_modules/mongodb/lib/cursor.js:226:59)
4|sweet    |     at Cursor.close (/home/raphael/sweet/node_modules/mongodb/lib/cursor.js:904:19)
4|sweet    |     at cursor._next (/home/raphael/sweet/node_modules/mongodb/lib/operations/cursor_ops.js:224:23)
4|sweet    |     at handleCallback (/home/raphael/sweet/node_modules/mongodb-core/lib/cursor.js:204:5)
4|sweet    |     at _setCursorNotifiedImpl (/home/raphael/sweet/node_modules/mongodb-core/lib/cursor.js:433:38)
4|sweet    |     at self._endSession (/home/raphael/sweet/node_modules/mongodb-core/lib/cursor.js:441:46)
4|sweet    |     at ClientSession.endSession (/home/raphael/sweet/node_modules/mongodb-core/lib/sessions.js:129:41)
4|sweet    | Tue, 18 Jun 2019 11:11:23 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at server.js:49:9
4|sweet    | Tue, 18 Jun 2019 11:11:23 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29
4|sweet    | (node:13351) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
4|sweet    | (node:13351) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

**Pull request merged**
