### PR TITLE
I guess this is about community post images now?

### PR DESCRIPTION
**Pull request by toBeOfUse**
This will find out if I'm right about the cause of issue #21. Then you can uncomment the stuff that'll try to fix the problem if you want. I'm assuming you can just run this on the server (presumably concurrently with the main program) and get the like console.log messages from it? I have no idea what that setup is. If not, I guess this'll have to become a `module.exports = function(app, passport) {app.get('/test/smol-db-check', function(req,res){ doot doot doot })}` kind of thing where the messages I'm logging here are put in a string and then sent as a response at the end. Or... email them to yourself, or something.

### CODE REVIEW

**Comment by lowercasename** [comment]
Well that was fun - 17 individual instances of users without a community in their document (no instances of communities without users in their documents). All fixed now, but we should definitely find a way to resolve this permanently. I agree that there's no real reason of keeping data in two places - or rather, it's great if we do keep data in two places for ease of use, but not if it isn't kept synchronised properly!

**Comment by toBeOfUse** [comment]
Did you note if Mags and Reading for fun were in there?

**Comment by lowercasename** [comment]
They were! I've kept the logs, I just don't want to post them publically - I'll email them to you.

**Comment by toBeOfUse** [comment]
I broke community post image posting with the last update! I didn't realize that community posts used a different api method than regular posts and so that method didn't get the code for moving the images from temp to regular image storage. Fixed now. This ought to be merged.

**Comment by lowercasename** [comment]
They probably shouldn't use a different API though, should they. The only difference appears that the community API uses the /api/... route syntax, which I prefer to /createpost, and obviously it needs a few extra params to work, but there's no reason whatsoever why they can't use the same API!

**Comment by lowercasename** [comment]
There should be a unified `/api/post/create` API, because later we can extend `/api/post` with `/api/post/edit` and unify it with an updated `/api/post/delete`. Obviously these are things I should have done from the beginning. I can't do that at the moment, but soon!

**Comment by lowercasename** [comment]
(You are of course welcome to do it if you have the time - I imagine `/api/post/create/:type/:communityid/:communityurl` is a good syntax.

**Comment by lowercasename** [comment]
Am done now! Found a new problem in re. the image display API which I've made an issue - the image API also revealed my server's directory structure when an image file didn't exist so I've fixed that now. Tell me when you're done making changes and I'll merge this and push it straight to the server as it's got a bunch of pretty critical updates

**Comment by toBeOfUse** [comment]
Yeah no it's probably fine now. This time.

**Comment by toBeOfUse** [comment]
What do I always say? "Working code" is just a term for code that hasn't been thoroughly tested yet

**Comment by lowercasename** [comment]
> What do I always say? "Working code" is just a term for code that hasn't been thoroughly tested yet

Ah, very good, sweet now has a motto.

**Pull request merged**
