### PR TITLE
Feed requests based on timestamps instead of page numbers

### PR DESCRIPTION
**Pull request by toBeOfUse**
Because the posts the server considers as the contents of page 1 and the posts the server considers as the contents of page 2 might change between requesting page 1 and requesting page 2, causing your displayed pages not to line up with each other. Maybe someone made a new post, making the post at the bottom of page 1 load again, as the server now thinks of it as belonging on page 2, like I think happened [here](https://sweet.sh/vonbees/5ivl-M1BY). Maybe someone deleted a post, causing a post to be pulled back up into page 1 from page 2, and hence will not be displayed when you load page 2. Maybe you went and followed or unfollowed someone and then scrolled down on your home feed! That could doubly-load or skip posts en masse. Specifically asking for posts just older than the oldest post currently loaded fixes this. Note that this assumes no two posts will have exactly the same relevant timestamp, which is true probably. Not well tested yet, at least for far as tag and search feeds.

### CODE REVIEW

**Comment by lowercasename** [comment]
Oh shit, this is just out of nowhere cool!!!


________________________________

**Comment by toBeOfUse** [comment]
This seems pretty stable right now, it just contains a few small extra things, make a new post by drag and dropping or pasting an image into the editor with network throttling on for the full effect

**Comment by toBeOfUse** [comment]
I'm going to leave this pull request here, I guess, it probably works and should be poked and prodded a little and then merged

**Comment by lowercasename** [comment]
I'm so into the new features 😍 With the progress bar, the copy-pasting of images, and all, this is just beginning to feel like a mature powerful website, I'm really into it.

One bug I _think_ I've spotted is that gifs which are pasted in (or at least specifically [this, very important gif](http://giphygifs.s3.amazonaws.com/media/eiwhyYQxUR4hq/giphy.gif)) don't get pasted in as gifs - or stop being gifs somewhere along the line.

**Comment by toBeOfUse** [comment]
yes, unfortunately there is no standard for copying animated images into or
out of the clipboard - the default copying behavior on windows, for
example, will put the copied images into one of these formats:
https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats
none of which allow for animations. for the same reason, i can't copy pngs
without them losing transparency - there is no standard clipboard format
that holds images with it. as far as i know, it's roughly the same
situation on os x.

**Pull request closed without merging**
