### PR TITLE
Misc issues cleanup

### PR DESCRIPTION
**Pull request by toBeOfUse**
#95 #96 #90 #83 #70 (?) #94 #87 #60 fixed. All fairly small, shouldn't be too terrible

### CODE REVIEW

**Comment by toBeOfUse** [comment]
We aren't still using the in-browser "autosize" or handlebars scripts, are we? I removed the links to them and it didn't seem to break anything

**Comment by toBeOfUse** [comment]
#60 but also I'm going to add that no two communities should have exactly the same name (in addition to obviously you can't have two communities with the same url.)

**Comment by toBeOfUse** [comment]
So:

image
tribute has this massive commented out area at the bottom:

image

which the minifier obviously removed, hope that wasn't necessary for... something

**Comment by toBeOfUse** [comment]
Yeah don't merge rn community vote fix still needs finishing fixing...

**Comment by lowercasename** [comment]
I just pushed a local version of JQuery to master and the prod server because I started, for no new reason I could see, getting CORS errors on JQuery, so the whole site crashed for me!

**Comment by toBeOfUse** [comment]
Final to-do:
* make and use a new db schema/collection for community name + url placeholders
* test to make sure votes no longer start when you haven't actually changed anything
* when someone is banned, are their votes currently dismissed? bc otherwise i could see some bad actor making 100000 votes and messing up the page and no way to stop them
* make sure the person behind each vote post request actually belongs to the community
* also make sure anyone casting a vote actually belongs to the community and hasn't cast a vote on this already
* check incoming email times/time zones in user settings, it looks like some browsers allow an empty time to be set even when you make that field "required." also, look at the alternate email time input that apparently safari has to use
* maybe clean up new notifications code + check to see what happens if a user requests notifications but then denies us notifications permissions
* double-double-check post visibility rules actually working
* finally close all the relevant issues!
* why is it called "red hair." it's orange.

Push notifications more or less work after you request them on the settings page in Chrome and Firefox on Windows when you have those browsers sitting open and just generally, a lot like a native app, for mobile Chrome on Android (with a ≈ 45 second delay if you've been away from the site for a while.) Note that to get them working on iPhone we'll have to register with Apple and get an official security certificate and stuff so I'll note that down as the probable subject of a future pull request. Also, if you do test them with a phone they didn't work for me without https, even within my home network, so there's some extra code for that commented out in server.js right now, you have to use something like mkcert to generate a certificate for your local ip address and then install its rootCA certificate on your phone. Good luck

I've put a list of future pull requests on the wiki, feel free to add to it. Maybe replace the text editor next bc if we choose our replacement well it should be quick and easy. I'm scared to touch that "# symbols in link urls" issue because regex and I generally tend not to get along? I guess it's just a special case where you have to ignore #s if they're within the ... in <a href="...">... Still scary bc what if someone makes a post where they type <a href="..."> and then put the whole actual post within the ... there and then expects tags to work in it. We'd have a riot on our hands

**Comment by toBeOfUse** [comment]
It appears God has punished me for getting instantly distracted from to-do lists I've just written by making me insanely bad at regexes

regex

**Comment by toBeOfUse** [comment]
My very simple although slightly hacky video embedding solution was to transform all youtube urls that are added in with in a line to themselves into embedded videos, and I've just implemented it fairly successfully, let me know what you think about it, I'm open to constructive criticism

**Comment by toBeOfUse** [comment]
Also it appears that community vote expiration is handled by some timers, keep in mind that such things all go away when you restart the server and need to be re-created after that event (and also checked to see if any votes expired while the server was off), the reason is that anything that you or your database software does not explicitly write to a disk is stored in "ram" (generally just referred to as "memory" in this context) for as long as your program might still use it, and ram needs a constant power source or everything in it goes away, and it loses power as part of the restart process, in fact I think that's most of the point of the restart process

**Comment by toBeOfUse** [comment]
I see there's a "comments" field in the vote schema, seems like a good idea, maybe that should be put on the list of things to be implemented one of these days

**Comment by toBeOfUse** [comment]
If we want to later we can do something to keep links to the community from breaking when the url changes (I guess just reserving the old url and putting a redirect there) but I can't be bothered right now

**Comment by toBeOfUse** [comment]
As far as I know everything actually works fine at this point but I'm also gonna change the votes to last x amount of minutes instead of days so I can actually test it out. Note to self: do not, I repeat, do not, forget to change this back

**Comment by toBeOfUse** [comment]
I'm still not super in favor of creating two visibly different kinds of posts, but if we ever just added an option to switch to an essay-style text editor for writing stuff, the ability to manually place images in between paragraphs in a post would be lovely. If I ever write something long I do appreciate the ability to break it up with illustrative images even if the form has been kind of degraded by like Buzzfeed articles that have a gif after every other sentence. And it shouldn't be too difficult, I think all of those potential text editors you linked to have support for placing images within a document, although of course we'd still have to control the styling and display of the images to keep things looking unified. Hopefully I've done that with this Youtube video embedding experiment

**Comment by toBeOfUse** [comment]
Ok, as far as I can tell this one is good to be merged and pushed, I remembered to change the vote length thing back.

**Comment by toBeOfUse** [comment]
Ok, _now_ it's ready

**Comment by toBeOfUse** [comment]
I've gone ahead and disorganized all the css for image sizes, now single vertical images are taller  (max-height of 550px) and the containers for other images have a minimum aspect ratio of 3:2. Setting an aspect ratio of 3:2 is somewhat elitist as it's the default output format of traditional expensive film stuff and also expensive digital cameras, but setting a more egalitarian minimum aspect ratio of 4:3, as would fit ordinary cell phone cameras and the like without blank space on the sides, makes for some large images, they would look like this (1920x1080 screen):

image

So I haven't done it, and think whatever you think about that. Aside from your no doubt multitudinous worries about whatever it is I've done here that wasn't in the initial description I gave, this is still again ready to be merged and pushed, also I've just found out that you can't even do push notifications to Apple devices without paying them like $100 a year so that's only going to be available on PC/Android as far as I'm concerned ever, which should hopefully offset the elitism of the image aspect ratio a little.

**Comment by toBeOfUse** [comment]
ok NOW it's ready to push

**Comment by toBeOfUse** [comment]
npm install compression please, I'm requiring and using it in the code and it reduced our website payload for my test user's home page from 2.7 mb to 1.6 mb (≈40% reduction in size) through gzip I think and black magic

**Comment by lowercasename** [comment]
Gzip is already implemented serverside - is there a way to check the size of the downloaded payload on the production server? I will push this soon when I get a chance away from work, if you decide that compression is worth installing as a module.

**Comment by lowercasename** [comment]
Also, with my apologies that I haven't had a chance to have a look at this before - could we have it so that video embeds come up initially as link previews (maybe using the design in the abandoned link previews PR), which can then dynamically be populated as embeds through JavaScript when they're clicked on? this is for a couple of reasons: video embeds in iOS are kinda hellish, so people might prefer to open them in an app on mobile (which I _think_ you can do by clicking the title of the embedded video once it's loaded?); they'll take up less room while scrolling; some people (me) just kinda hate embedded content because you accidentally tap on it while trying to scroll and so forth; it means people have an opportunity to opt out of the trackers which I'm sure are attached to embedded videos; and it might mean the feed take less time to load - I don't know if embedded videos preload anything before they're played, but my gut says probably. We could slap a play icon in a circle on the image preview part of the link preview to make it blatantly obvious that the video will play once clicked (and that way if people want just the link, they can right click on the link preview and copy it).

**Comment by toBeOfUse** [comment]
> Gzip is already implemented serverside - is there a way to check the size of the downloaded payload on the production server? I will push this soon when I get a chance away from work, if you decide that compression is worth installing as a module.

Your server's gzipper must be swinging and missing a fair but, this is the "payload size" audit for the actual currently running website:

image

And here it is for my test server:

image

Some of the files are smaller on the test server than on the actual server because I minified them in this pull request, but I didn't touch all.js (that's the fontawesome one) and its size decreased significantly. (I just made sure that I didn't touch all.js by downloading the actual file in current use from the production server, and comparing the size of it to the one on my test server, and they're both exactly the same total size (1.1 mb.)) And I can look at the js files I'm getting from the real server in the network panel and it doesn't say anything about gzip:

image

vs. the same file from the test server:

image

If you can gzip using some other mechanism on the production server instead of using the compression module, that's fine by me, as long as it demonstrably actually covers stuff like all.min.js, which is otherwise quite large, but meanwhile I was running this audit program and it was like "don't you know what gzip is you idiot. you buffoon." and I had to be like "no" and google it and now here we are

**Comment by lowercasename** [comment]
well i'm fully convinced compression is the way to go; for reference this is the gzip directive i'm using: https://caddyserver.com/docs/gzip

**Comment by lowercasename** [comment]
(using caddy for actual stuff does make me always feel a tiny bit:

source

...but hey nothing bad's happened _yet_)

**Comment by toBeOfUse** [comment]
All right, see what you think.

image

**Comment by toBeOfUse** [comment]
I mean, in your defense, that's a very valid gzip strategy, that should have been working. Also, are the link preview video embed things allowed in comments or not? I'd just have to change one "true" to a "false" to block them there.

**Comment by toBeOfUse** [comment]
The trick is picking the right one.

**Comment by toBeOfUse** [comment]
Anyway, the only thing right now is maybe test out the link preview stuff on your phone, it was fighting me on mine (the CSS that was there wasn't restricting the image's width and it was shooting off the side of the page) and I'm not 100% on what I just did to fix that.

**Comment by lowercasename** [comment]
I guess... link previews should be allowed in comments? Honestly I hadn’t considered it!


________________________________

**Comment by lowercasename** [comment]
Your work is gorgeous and stalwart, I will check more after the weekend (sorry for slowing down your pace of work)


________________________________

**Comment by lowercasename** [comment]
Why am I unable to switch to this pull request locally and push to it, help, why is git so hard

**Comment by toBeOfUse** [comment]
I've "requested a review" from you, see if that helps, with every other pull request I think it set you as the reviewer automatically so not sure what's up this time

**Comment by lowercasename** [comment]
I have no damn idea what's going on with this PR and why I can't add to it, so I'm just going to merge it into master and then create a new PR with some small changes, subject to your approval!

**Pull request merged**
