### PR TITLE
This mostly just contains dark mode stuff right now I think

### PR DESCRIPTION
**Pull request by toBeOfUse**
CSS sucks so bad. I hate it so much. Anyway, I just updated that one css cleanup pull request I made a long time ago to incorporate the stuff added since it and now bootstrap's huge css thing is not linked in anymore and also the css file we will use is marginally better-organized into sections by comments. If you can find any glitches introduced, fix them, otherwise this should be merged and the new styles_with_stolen_bootstrap_stuff.css used from now on so I don't have to update it again.

### CODE REVIEW

**Comment by toBeOfUse** [comment]
what does :root even DO? Nevermind, don't tell me, I don't want to know. Also, I've been minifying the new css file as I go, so keep in mind that the minified version is what's currently linked to in main.handlebars if you find something you need to change. But I do think that this is fine, it was working a long time ago and just needed a few things updated because of css changes made since which I was happily able to easily find by asking github for the right diff, or if it's not ready I'm excited to find out why and how

**Comment by toBeOfUse** [comment]
For reference, just [the bootstrap css file that was linked in](https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css) is 10,341 lines long when unminified by unminify.com, and that's without the sweet-specific stuff in style.css; style_with_stolen_bootstrap_stuff.css definitely has a few unused classes in there somewhere but is "only" 3,372 lines long, total. 10,341 lines of just css, the horror

**Comment by lowercasename** [comment]
So I decided to ruin everything by introducing another preprocessor into our lives! Say hello to our new friend Sass!

The raw (S)CSS lives in the scss/ directory. The `npm start` script also launches the `node-sass` preprocessor, which watches that directory and updates and minifies style.css in the public/css directory as scss files are changed. You'll need to run an npm update to get node-sass.

Sass is genuinely great for three reasons: simple imports, which keep our styles structured, which I've already begun doing; nesting more specific rules inside other rules, which is just a godsend for big HTML structures like ours; and variables, which will help us finally get things like colors under control.

I've started moving through your stolen Bootstrap stuff file and putting rules in sensible locations in SCSS files. The Sass documentation is great if you haven't used SCSS before!

**Comment by toBeOfUse** [comment]
Back when I originally took out bootstrap the little downwards-pointing
triangle under the tooltips that come up when you hover over
users/communities in a sidebar went away, that was my only outstanding
issue where I couldn't reconstruct it by scraping content from more
bootstrap css-like files, maybe sass can fix that

**Comment by lowercasename** [comment]
jRhnQro copy

(sorry)

**Comment by lowercasename** [comment]
All alerts are now the same (hopefully pleasantly pink) color and use the class `.message`. Messages to warn the user of an error or problem take the addiitional class `.alert` (and pulse).

I've made some decisions with the colors here (specifically the 'pink' variables) which you may not be in favour of - if so, please change them to a more pleasant shade! I'm not commited to the whole pink/red thing.

**Comment by toBeOfUse** [comment]
I'm kinda curious about how with the old bootstrap stuff you could actually see the scss files where stuff was coming from in the inspector:

image

Is there a way to make that happen with these new scss files? It seems like it would be handy to know what scss file you need to go to to make a change to a rule.

Love the new buttons, by the way. It is true that having three big red (ish) buttons in a row like this:

image

Startles my brain a little more than I think is necessary, given that they aren't hugely important buttons that need attention all the time. But I definitely like it overall.

**Comment by lowercasename** [comment]
Did I just eat your commit in which case I'm so sorry! GitHub went weird on my end

**Comment by lowercasename** [comment]
I would like to stress the experimental navbar is _experimental_ and can be disabled in index.scss by removing the word 'experimental'. I dunno man. Maybe I wanted a change. Maybe I'll sleep on it and decide it's atrocious. It also doesn't work on mobile. I just dunno.

**Comment by lowercasename** [comment]
Oh god yeah, I kind of did a dark mode thing here but now I need to double-check some of the CSS in the other branch, and also there are still some outstanding CSS issues (and also of course the dark mode setting isn't being saved)

**Comment by lowercasename** [comment]
Maybe we should save this for the next update...

**Comment by lowercasename** [comment]
https://fontawesome.com/icons/dumpster-fire?style=solid I've found it

**Comment by lowercasename** [comment]
I have done dark mode by pillaging this pull request, it is now DONE, I am CLOSING it, we shall NEVER SPEAK OF IT AGAIN.

But first, let's take a moment to remember what might be the funniest comment on this repository to date:

> yeah, they look like they'll do nothing, and if you google it it'll say that they do nothing, but if someone goes to the search page and inputs the term "garbanzo bean" without them being there all of the user's text will be right-aligned until the end of the next full moon. this is why i hate css, browsers should just give us the window size and the text contents and a few basic shapes to start with at most and just let us write a function to position everything manually by pixel coordinates ourselves. it would take about 50 years to get anything close to this complicated done but at least the time wouldn't be spent googling what it means to have -webkit-tap-highlight-color be set to "transparent" instead of "light-grey." or to have -webkit-text-decoration-skip set to "objects" instead of some similar philosophically defined category like "animals-but-not-the-ones-with-souls."

thanks @toBeOfUse

**Pull request closed without merging**
